### ISSUE TITLE
`Unexpected end of JSON input` error when querying `accounts`

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1026]
<img width="2032" alt="Screen Shot 2024-06-03 at 9 25 22 AM" src="https://github.com/Granola-Team/mina-indexer/assets/19426804/1d5812b0-a527-490b-942e-5bb42bb5b11d">
<img width="2032" alt="Screen Shot 2024-06-03 at 9 25 05 AM" src="https://github.com/Granola-Team/mina-indexer/assets/19426804/2f149b3d-3c90-4432-bee0-8e23feac7c50">

**Comment by trevorbernard** [comment]
I believe this error was caused the the CORS issue we briefly had. I haven't been able to recreate this issue on prod

**Comment by robinbb** [comment]
@n1tranquilla Back to you to repro.
