### ISSUE TITLE
Inconsistent return types for empty data

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1028]
```{"data":{"accounts":null}}```
```{"data":{"blocks":[]}}```

**Comment by Isaac-DeFrain** [comment]
Would you prefer `{"data":{"accounts":[]}}`?

**Comment by robinbb** [comment]
@Isaac-DeFrain I think that he simply wants consistency. I think that if the return value is expected to be an array, and the call was successful, then the returned value should be an array.

**Comment by n1tranquilla** [comment]
It has caused a bug in the UI, which I have worked around. I also agree with the above comment

**Comment by Isaac-DeFrain** [comment]
On it

**Comment by Isaac-DeFrain** [comment]
All array responses will no longer be wrapped in an option

**Comment by Isaac-DeFrain** [comment]
Just to clarify, these are currently consistently returning `Option<Vec<T>>`s. The problem is that GQL annoyingly flattens `Some([...])` to `[...]` giving the appearance of inconsistency. Having said that, I'll change our GQL endpoints to simply return `Vec<T>`s to avoid downstream effects.
