### ISSUE TITLE
Problem: `server sync` is redundant, and should be removed to avoid confusion

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1033]
'mina-indexer server sync' is the same as 'mina-indexer server start' if you have a database, but fails if you don't have a database. So, it is useless, and confusing. Remove 'sync'.

**Comment by robinbb** [comment]
... with the understanding that the functionality of 'sync' is mostly preserved by way of 'start'.

**Comment by jhult** [comment]
Adding comments from internal Slack:

> `start` initializes the Indexer from a directory of blocks/staking ledgers without the presence of a database; maybe a "better" name is new??

More below:

This is how @Isaac-DeFrain thinks about the 3 initialization modes:
- `start`
  - In the absence of a database, ingest blocks and staking ledgers with canonical chain discovery
  - In the presence of a database, `start` defaults to `sync`
- `sync`
  - Requires existing database/snapshot
  - This is our "quick sync" feature which rebuilds the in-memory witness tree from the supplied database/snapshot; if you trust the source of the snapshot, this is what you would use as it's more performant than `replay`

- `replay`
  - requires existing database/snapshot
  - This "replays" all database events to rebuild the witness and does some data consistency checks in the process

**Comment by jhult** [comment]
Suggestion for redesigned CLI semantics:

- Normal start: `mina-indexer start ...`


- `mina-indexer start --config PATH`
  - Current equivalent: `mina-indexer start-with-config --path PATH (sp?)` 


- `mina-indexer start ... --self-check e`
  - Current equivalent: `mina-indexer start-with-self-check ...`

**Comment by jhult** [comment]
The `create-database` command should solve #1033

**Comment by robinbb** [comment]
Assigning @Isaac-DeFrain because he has #1203 and solving that one will resolve this one.
