### ISSUE TITLE
Add a large amount of staking ledgers to the prod deployment

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1046]

**Comment by n1tranquilla** [comment]
Will this include the current staking ledger? I need up-to-date staking ledger for the current epoch to be able to unblock one of my issues

**Comment by n1tranquilla** [comment]
https://github.com/Granola-Team/mina-block-explorer/issues/740 @robinbb

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/infra#21

**Comment by robinbb** [comment]
@n1tranquilla For now, we do have the current staking ledger, and I can see from the server logs that it is indeed ingested.
