### ISSUE TITLE
Add 10^5 blocks to the prod deployment

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1048]

**Comment by Isaac-DeFrain** [comment]
Related Granola-Team/infra#21

**Comment by robinbb** [comment]
Waiting for prior new prod data to be correctly employed by the mina-indexer. Then, I will be able to resume this.

**Comment by Isaac-DeFrain** [comment]
Are we ready to pump?

**Comment by robinbb** [comment]
@Isaac-DeFrain I think we are still blocked by #1106, #1108, and Granola-Team/mina-block-indexer#740

**Comment by robinbb** [comment]
Also blocked on Granola-Team/mina-block-explorer#820
