### ISSUE TITLE
Integrate with the Mina On-Chain Voting app

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1049]

**Comment by Isaac-DeFrain** [comment]
In what way specifically?

**Comment by robinbb** [comment]
I mean that the mina-on-chain-voting app should be altered so as to use only the api.minasearch.com as its back-end.

**Comment by trevorbernard** [comment]
> I mean that the mina-on-chain-voting app should be altered so as to use only the api.minasearch.com as its back-end.

@robinbb I ported it to mina explorer at one point in time but that might have been over a year ago. Should this be an on-chain voting app issue instead?
