### ISSUE TITLE
Investigate RocksDB batch writes

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1051]

**Comment by Isaac-DeFrain** [comment]
https://github.com/facebook/rocksdb/wiki/Basic-Operations#non-sync-writes

**Comment by Isaac-DeFrain** [comment]
https://rockset.com/blog/optimizing-bulk-load-in-rocksdb/

**Comment by Isaac-DeFrain** [comment]
https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks#test-1-bulk-load-of-keys-in-random-order

**Comment by robinbb** [comment]
I would stay away from the "build SST files on your own" option. We don't need performance enough to want to make the product any more complex. I was hoping for a "turn off indexing, ingest, turn on indexing" option.

**Comment by robinbb** [comment]
Do the official docs offer any hints about how to achieve what we want?

**Comment by n1tranquilla** [comment]
I did a deep dive into this and have already converted many of the inserts to batch writes. The improvements was marginal.
