### ISSUE TITLE
Simplify and standardize database key formats

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1055]
Our current database schema consists of 80 column families. The naming conventions and encoding/decoding mechanisms for these column families lack consistency and type safety. This inconsistency makes it difficult to manage the database and can lead to potential errors in data retrieval and storage.

**Comment by jhult** [comment]
Related to #799

**Comment by trevorbernard** [comment]
We should make them strongly typed to avoid manually encoding and decoding
