### ISSUE TITLE
Problem: %ge complete in staking page displays more than 100%

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1058]
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/550475/260978e0-b551-431f-b304-2e7fa16d1d36)

**Comment by trevorbernard** [comment]
I'll look into it

**Comment by trevorbernard** [comment]
Created the following issue: https://github.com/Granola-Team/mina-indexer/issues/1060
