### ISSUE TITLE
Problem: the display for epoch 0 shows no data

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1059]
![Image](https://github.com/Granola-Team/mina-block-explorer/assets/550475/ff4c4752-5e16-40a2-9122-cc223346fc3a)

... even though there is an epoch 0 and the data is available in the staking ledgers directory, and I can see from the server logs that it was ingested.

**Comment by trevorbernard** [comment]
The underlying problem is that epoch 0 & 1 share the same ledger hash and epoch 1 overwrites the former.

**Comment by Isaac-DeFrain** [comment]
I got this

**Comment by robinbb** [comment]
Not fixed by #1102.
