### ISSUE TITLE
Account endpoint does not return the username

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1064]
We still have to visit ME to get the username.

ME: https://minaexplorer.com/wallet/B62qjzJvc59DdG9ahht9rwxkEz7GedKuUMsnaVTuXFUeANKqfBeWpRE `MinaExplorer Name Service`
MS: https://minasearch.com/addresses/accounts/B62qjzJvc59DdG9ahht9rwxkEz7GedKuUMsnaVTuXFUeANKqfBeWpRE `Unknown`

<img width="730" alt="Screen Shot 2024-06-05 at 1 48 17 PM" src="https://github.com/Granola-Team/mina-indexer/assets/19426804/eeb54711-7afe-4fbb-ba78-de484a15e3fb">

**Comment by trevorbernard** [comment]
We do grab the username from the memo. The problem is that there aren't many in the first 10^5 blocks

**Comment by robinbb** [comment]
Dup of #1067
