### ISSUE TITLE
User Commands: "from" filter not working 

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1074]
Steps to reproduce:
1. visit minasearch.com/commands/user
2. "look for whisperit#8145" memo
3. filter by "B62qoaMj7u1JzuqXaBByQBL5jzqLguK8e7LHVPdY9LcvvLXK7HPsusD"

![2024-06-06 08 54 23](https://github.com/Granola-Team/mina-indexer/assets/19426804/426169d8-3022-456b-803b-12e66f5e1d45)

**Comment by Isaac-DeFrain** [comment]
Related #1072

**Comment by n1tranquilla** [comment]
Non-issue
