### ISSUE TITLE
Problem: `GIT_COMMIT_HASH` is required to be set else the compiler complains

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1080]
This affects running tests and tools from your editor. E.g. clippy, check, etc.

**Comment by trevorbernard** [comment]
To just ride yourself of the compile error, it might be sufficient to just export that var in `.envrc`. Untested

**Comment by robinbb** [comment]
I think Trevor fixed this with a .envrc entry.
