### ISSUE TITLE
Problem: the Nix-built image does not work

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1083]
...due at least to #1082, so this issue is blocked on that.

**Comment by trevorbernard** [comment]
This is the error we get when trying to run the docker image built against `5d8a6adc`
```
docker run --rm -it mina-indexer:5d8a6adc mina-indexer server start
thread 'main' panicked at src/block/genesis.rs:18:9:
Genesis block does not exist at /build/source/rust/tests/data/genesis_blocks/mainnet-1-3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ.json
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by robinbb** [comment]
Right, because it's looking for the genesis block at a directory (/build/source) that only exists at build time, not at run time. This is due to how set that path (using 'env!').

**Comment by robinbb** [comment]
Blocked by #1082

**Comment by trevorbernard** [comment]
The blocker has been resolved. https://github.com/Granola-Team/mina-indexer/issues/1082

**Comment by robinbb** [comment]
Confirmed. I will re-add the image build to the tier-2 testing.
