### ISSUE TITLE
Problem: B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va has too many records

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1108]
Paste B62qq3tqfdj19hqaVCozJFM2q9gT2WezQMaJMKD6wxyvK3fMpHiP9va into the search bar, you will see too many idential records in the spotlight page.

**Comment by trevorbernard** [comment]
This is likely a duplicate of the one @Isaac-DeFrain suggested I do

**Comment by trevorbernard** [comment]
@robinbb The issue is closed but the indexer in production hasn't deployed the new code yet

**Comment by robinbb** [comment]
Yeah, you're right, Trevor. My bad. I was too hasty. I see it is fixed, now.
