### ISSUE TITLE
Make `TxnHash` struct

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1109]
We should use `pub struct TxnHash(pub String)` over `String`

**Comment by trevorbernard** [comment]
We should strongly type all the things

**Comment by n1tranquilla** [comment]
There are some performance considerations around this. Currently we're passing around &str and refactoring to TxnHash(pub String) would result in many more memory allocations on the heap. There probably are some ways around this using [Cow](https://doc.rust-lang.org/std/borrow/enum.Cow.html), but I think it is a little beyond me at this moment.

**Comment by trevorbernard** [comment]
Cow isn't necessary if you aren't mutating a shared resource. Just pass in the &TxnHash. This feels like prematurely optimization. Even better would be to use the txh hashes binary representation as the value rather than it's string-ified representation.
