### ISSUE TITLE
Deploy all blocks to production

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1129]
Here, "all" blocks means most blocks. It means all the blocks that are in the S3-compatible storage bucket, but not necessarily *all* blocks.

**Comment by robinbb** [comment]
Blocked on back-end sometimes crashing. Waiting for a  few consecutive days of uptime.

**Comment by robinbb** [comment]
Blocking on #1139

**Comment by Isaac-DeFrain** [comment]
Since #1139 is finished, is this now unblocked?

**Comment by robinbb** [comment]
Blocked on general instability and the many issues in the Equivalence milestone.

**Comment by robinbb** [comment]
Blocked on #1218 and #1219
