### ISSUE TITLE
The web server starts before initial block ingestion is complete

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1144]
Although we can see blocks being ingested from the UI, this poses a problem for CI/CD if there is an already existing indexer running. It cannot grab the port and the indexer fails.

Move the starting of the web server until after we've finished the initial ingestion. This allows us to create the initial database in parallel.

**Comment by robinbb** [comment]
I would be okay with starting before the block ingestion is complete, too, but then we would have to expose the socket earlier and accept incoming messages on that from startup (not merely after ingestion).

**Comment by robinbb** [comment]
Related to #1151. Please coordinate, or combine into same issue.

**Comment by robinbb** [comment]
This is not the right problem. The real issue is that we must facilitate shutdown during ingestion. I will make an issue.
