### ISSUE TITLE
Duplicate internal commands

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1145]
`3NKP5eG9qvMbJM78thgQMvwnNnjrEkfcAfS31YbNNzeBsa8ADqPR`

<img width="1840" alt="Screen Shot 2024-06-13 at 1 26 24 PM" src="https://github.com/Granola-Team/mina-indexer/assets/19426804/771a5875-c54f-4b9a-bc02-914d96ddc7db">

**Comment by Isaac-DeFrain** [comment]
It depends on how we want to display this data. We store/show all fee transfers as they correspond to each user command. We could also aggregate all transfers from the same pk.

Do we want to display coinbases here? They’re already in the block spotlight

**Comment by n1tranquilla** [comment]
Does the "state hash" in this image indicate that internal commands are all part of the same block? If so, we should close this issue.

**Comment by Isaac-DeFrain** [comment]
Yes

**Comment by Isaac-DeFrain** [comment]
I think there is still a discussion to be had about how we should display this info

**Comment by robinbb** [comment]
Yes, this has been the eternal debate - whether to display the coinbases. Best not to have that discussion on a closed issue, however. I'm only commenting because I was @-mentioned.
