### ISSUE TITLE
Duplicate SNARKs

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1147]
https://minasearch.com/snarks?q-state-hash=3NKP5eG9qvMbJM78thgQMvwnNnjrEkfcAfS31YbNNzeBsa8ADqPR

<img width="1840" alt="Screen Shot 2024-06-13 at 1 37 30 PM" src="https://github.com/Granola-Team/mina-indexer/assets/19426804/c5a8f5e9-ba53-4892-afe6-63ec24f6c191">

**Comment by Isaac-DeFrain** [comment]
How do you know these are duplicates and not just two SNARKs by the same prover in the same block with the same fee? This is certainly possible

**Comment by n1tranquilla** [comment]
Closing as I can't prove duplication
