### ISSUE TITLE
Document REST endpoints

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1165]
- `/summary`
- `/accounts/{pk}`
- `/blocks`
- `/blocks/{state hash}`
- `/blocks/height={height}`
- `/blocks/slot={slot}`

**Comment by jhult** [comment]
https://docs.minaexplorer.com/rest-api

**Comment by jhult** [comment]
https://minataur.net/api/restful

**Comment by jhult** [comment]
Relates to #1166

**Comment by jhult** [comment]
Done: https://docs.minasearch.com/apis/rest
