### ISSUE TITLE
running `mina indexer client account --public-key <public-key>` on an up to date indexer results in an error

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#117]
The issue:

Asking the `mina-indexer` for account information after initialization on mainnet blocks results in a file error

`Error: IO error: While open a file for random read: /mnt/indexer-block-storage/rocksdb/005690.sst: Too many open files`

<hr>

Steps to reproduce:

1. Initialize the `mina-indexer` on mainnet blocks
2. run `mina indexer client account --public-key <public-key>` in another terminal

**Comment by robinbb** [comment]
Requires a passing CI test to be considered complete. Re-opening.
