### ISSUE TITLE
/summary endpoint is sometimes slow

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1171]
In FE tests, I notice sometimes a 30 second latency

**Comment by n1tranquilla** [comment]
It sometimes manifest in FE tests. I have not seen it recently.

**Comment by robinbb** [comment]
I think that @Isaac-DeFrain is working on this, based on his comment in #1176.

**Comment by robinbb** [comment]
Closing. Haven't seen symptoms in a while. May have been corrected by other work.

**Comment by Isaac-DeFrain** [comment]
This will continue to be an intermittent issue until we replace our deserialization of the best ledger (only to count the number of accounts) for a proper count which is updated with the best block/reorgs

**Comment by n1tranquilla** [comment]
I think this issue has fallen in priority. I think we should move it to the maintenance milestone @robinbb

**Comment by robinbb** [comment]
I think priority is the same, but not technically required for Equivalence milestone.
