### ISSUE TITLE
User commands have no concept of "counterparty" and "direction"

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1172]
For a given public key, we need to load chronological user commands whether the PK was the receiver or sender. We must also include the concept of counterparty and direction. 

The current "from" and "to" properties are inadequate for our purposes as a history of incoming and outgoing txn must be made from two separate queries. This has its problems. 

```
For example:
Let's say the latest 100 txn for a given PK were all "outgoing" and zero "incoming". In the FE, we load 50 outgoing, and 50 incoming. We will get 50 "outgoing" and then 0  "incoming" txn. 
```

Returning all txn related to a PK, augmented with "counterparty" and "direction" properties, we could formulate a proper chronological history of transactions for a given PK.

**Comment by trevorbernard** [comment]
We already support this query. Something like this will work.

```graphql
{
  transactions(query: {OR: {from: "PK", to: "PK"}} limit: 50, sortBy: BLOCKHEIGHT_DESC) {
    ...
  }
}
```

**Comment by n1tranquilla** [comment]
Ok, so I think I can iterate over the result, and add the concept of "counterparty" and "direction"
