### ISSUE TITLE
Obtain number of accounts without deserializing the entire ledger

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1176]

**Comment by Isaac-DeFrain** [comment]
Related to #945. Once #945 is complete, we can track the number of accounts in the ledger much more easily

**Comment by n1tranquilla** [comment]
Is this an Equivalence issue?

**Comment by Isaac-DeFrain** [comment]
I believe this is the cause of #1171

**Comment by robinbb** [comment]
Issues are better phrased as problems, as opposed to as to-do list items. This one is a "what to do" issue, whereas #1171 is phrased as a problem. So, the latter is the better issue, though this task may be the desired solution. I'll close this issue, and assign @Isaac-DeFrain the #1171 issue, with the understanding that the work involved is likely the same.
