### ISSUE TITLE
Can only query accounts by balance up to 9 million MINA without overflow

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1177]
The largest value that can be represented by i64 is documented here https://doc.rust-lang.org/std/primitive.i64.html#associatedconstant.MAX which corresponds to about 9 million MINA.

The AccountQueryInput needs to accept "String" type

**Comment by trevorbernard** [comment]
We use u64 internally to represent nanomina not i64

**Comment by trevorbernard** [comment]
Actually, the code gen tool for GQL did generate some i64. Will change

**Comment by n1tranquilla** [comment]
https://doc.rust-lang.org/std/primitive.u64.html#associatedconstant.MAX

> 18_446_744_073_709_551_615u64

This is 18 million MINA, which is still much lower than the largest balances

**Comment by n1tranquilla** [comment]
Actually, I am re-reading these. for i64, that's 9 **billion** and for u64, that's 18 **billion**. Why am I getting overflow errors when trying to convert??

**Comment by n1tranquilla** [comment]
This is a non-issue
