### ISSUE TITLE
Aggregate fee transfers by recipient

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1181]
All fee transfers to the same recipient should be aggregated into one fee transfer for the sum amount
![Image](https://github.com/Granola-Team/mina-indexer/assets/42081488/9d11fd6e-97db-4687-8235-10565f2ca5bf)

**Comment by robinbb** [comment]
@Isaac-DeFrain This had to be rolled back, so I will re-open https://buildkite.com/granola/mina-indexer-tier-2/builds/133#01902f18-9bd7-4775-acfc-f691eddca3e6
