### ISSUE TITLE
Problem: can't discover the supported database version from client

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1190]
As a sysadmin, I would like to be able to discover the supported database version on the command line so that I can discover whether existing databases are compatible with the instance of the server that I am about to deploy.

**Comment by robinbb** [comment]
Blocking #1194

**Comment by robinbb** [comment]
The idea is to avoid starting a server simply to determine the database version.

**Comment by jhult** [comment]
Addressed by https://github.com/Granola-Team/mina-indexer/commit/114325439cc3c5055d4c9f13a3c16b1faec5d141
