### ISSUE TITLE
Add count of staking ledger accounts to GQL

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1195]

**Comment by jhult** [comment]
Loosely relates to #1130

**Comment by robinbb** [comment]
Required for "pagination" number (x of y of z - this issue is about z).

**Comment by n1tranquilla** [comment]
Blocks: https://github.com/Granola-Team/mina-block-explorer/issues/911

**Comment by n1tranquilla** [comment]
The [test](https://github.com/Granola-Team/mina-indexer/blob/5d796e329154946b468c28d064f2588d8d2fdf21/tests/hurl/stakes.hurl#L319C1-L339C16) gives false feedback. I have reproduced this test and found a different result.

Here is how to reproduce:

Query:
```
query StakingLedgersQuery($limit: Int = 10, $query: StakeQueryInput!) {
  stakes(limit: $limit, query: $query) {
    epoch_num_accounts
    pk_epoch_num_blocks
    epoch_num_blocks
  }
}
```

Variables:
```
{
  "limit": 1,
  "query": {
    "epoch": 1,
    "ledgerHash": "jx7buQVWFLsXTtzRgSxbYcT8EYLS8KCZbLrfDcJxMtyy4thw2Ee" 
  }
}
```

response:
```
{
  "data": {
    "stakes": [
      {
        "epoch_num_accounts": 0,
        "pk_epoch_num_blocks": 877,
        "epoch_num_blocks": 10350
      }
    ]
  }
}
```


![Image](https://github.com/Granola-Team/mina-indexer/assets/19426804/c80dd1bd-1886-46ee-a0af-6e367cde590e)

**Comment by trevorbernard** [comment]
There is something strange happening with the about query because the following returns correctly:

```
query Foobar {
  stakes(query: {epoch: 1}) {
    pk
    balance
    nonce
    chainId
    epoch_num_blocks
  }
}
```

**Comment by jhult** [comment]
I just [tried](https://api.minasearch.com/graphql), and it seems to be working for me...

<img width="1189" alt="image" src="https://github.com/Granola-Team/mina-indexer/assets/9849069/f2430056-c2c9-464e-8cb0-c83570fe0ff0">

**Comment by robinbb** [comment]
It would work, or not, depending on whether prod is ingesting or not ingesting.
