### ISSUE TITLE
Summary endpoint is missing total number of non-canonical blocks

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1199]

**Comment by robinbb** [comment]
Does it provide "total blocks"? "total canonical blocks?" Isn't blockchain height the same as total canonical blocks?

**Comment by Isaac-DeFrain** [comment]
Yes, blockchain length is equal to the number of canonical blocks. We already include the total number of blocks. So we just need to do some arithmetic.
