### ISSUE TITLE
Watched directory block reading fails when file is a hard link

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#1219]
https://en.wikipedia.org/wiki/Hard_link

**Comment by jhult** [comment]
This might a code area to explore: https://github.com/Granola-Team/mina-indexer/blob/main/rust/src/block/precomputed.rs#L191

**Comment by robinbb** [comment]
Ingestion works - files that are in the blocks directory when the mina-indexer starts. But, files that are added later are not recognised.

**Comment by jhult** [comment]
This may be a dupe of #1218

**Comment by n1tranquilla** [comment]
The watch dir appears to be broken. @jhult  and I cannot find any evidence that watch dir is ingesting blocks.

**Comment by jhult** [comment]
macOS may ignore hard links: https://github.com/notify-rs/notify/issues/374

**Comment by robinbb** [comment]
Check for faulty code, mishandling of the staking directory command line option, I suggest.
