### ISSUE TITLE
No test in regression suite to prove that watch dir ingests blocks

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1223]
Relates to https://github.com/Granola-Team/mina-indexer/issues/1219

**Comment by trevorbernard** [comment]
Here is evidence: https://github.com/Granola-Team/mina-indexer/blob/main/tests/regression.bash#L480

**Comment by robinbb** [comment]
@trevorbernard I think this issue was for the directory specified by `--watch-blocks-dir`, not `--blocks-dir`.

**Comment by robinbb** [comment]
In any case, the point is moot, and the issue can be closed, because there is no longer any `--watch-blocks-dir`.
