### ISSUE TITLE
Problem: database is not compacted before a snapshot

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1228]
... this means that databases/snapshots are enormously bigger than they need to be. For example, on the current tier3 testing machine, the database snapshot for block height 123,456 is 28.3 GB, but the database snapshot for block height 200,000 is 21.3 GB. So, the smaller database could likely be shrunken to 1/2 its size, at least, with compaction. As another example, 2 different database snapshots of database containing up to block heigh 270,000 are 34.7 GB and 17.3GB, respectively. This is again off by a factor of 2. Presumably, this means that, by coincidence, the second database was partially compacted when snapshotted.

This may simply be a matter of calling the Rust equivalent of DB::CompactFiles before snapshotting (and after waiting for results).

**Comment by robinbb** [comment]
This is urgent because the extra dozens of GB of data are causing very long upload/download times that affect our deployment and CI, unnecessarily.

**Comment by jhult** [comment]
Interesting note I found regarding compaction:

```
impl CompactOptions {
    /// If more than one thread calls manual compaction,
    /// only one will actually schedule it while the other threads will simply wait
    /// for the scheduled manual compaction to complete. If exclusive_manual_compaction
    /// is set to true, the call will disable scheduling of automatic compaction jobs
    /// and wait for existing automatic compaction jobs to finish.
    pub fn set_exclusive_manual_compaction(&mut self, v: bool) {
```

**Comment by jhult** [comment]
Which option should we implement?

1. Force compaction when creating a snapshot
2. Provide an option to compact when creating a snapshot and default to yes
3. Provide a separate CLI command to compact the database
4. A mixture of 2/3

**Comment by robinbb** [comment]
2,3,4 are all too complex. Simply do 1.

**Comment by robinbb** [comment]
Waiting for automatic compaction jobs to finish suffices. Too bad about CompactFiles, but there are other ways to wait for compaction to complete, no?

**Comment by jhult** [comment]
It seems like with the current code in `main`, this may be solved.

**Comment by robinbb** [comment]
Closing. #1243 better represents the problem.
