### ISSUE TITLE
The unavailability of staking data during ingestion is causing 10h CI outages on the FE

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1232]
A solution would be to ingest staking data first.

**Comment by robinbb** [comment]
Another solution is to cease using an external service for testing in CI.

**Comment by n1tranquilla** [comment]
I think the indexer is usuable enough now that deploying it during CI for the first 10k blocks would be a fine solution, and probably the most stable one for CI.
