### ISSUE TITLE
Assertion error on ingestion

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#1236]
```2024-07-02T02:13:25.681911+00:00 - DEBUG Looking for witness tree root block
thread 'tokio-runtime-worker' panicked at src/state/mod.rs:1004:17:
assertion `left == right` failed
  left: Some(37271)
 right: Some(37261)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by jhult** [comment]
https://github.com/Granola-Team/mina-indexer/blob/main/rust/src/state/mod.rs#L1004

**Comment by Isaac-DeFrain** [comment]
Do we have evidence that this happens with consistent db versions?

**Comment by Isaac-DeFrain** [comment]
I'll add some more context to start

**Comment by robinbb** [comment]
No, this could indeed have been due to failure to update database versions.

**Comment by robinbb** [comment]
See also #1246

**Comment by robinbb** [comment]
@Isaac-DeFrain I'm comfortable closing this in favour of #1246, for now. Unless you know what is wrong from the code (you can see that the assertion should indeed not always hold), then I suggest closing.
