### ISSUE TITLE
pwait is missing on macOS

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#1238]
https://stackoverflow.com/questions/1058047/wait-for-a-process-to-finish

**Comment by jhult** [comment]
I tried several solutions from the StackOverflow question. However, I was not able to make those work.

I think rewriting the waiting for process in Ruby may be the best solution. Assigning back to @robinbb.

**Comment by trevorbernard** [comment]
As Robin mentioned, it's probably best to implement this in Ruby instead of "bash-and-friends" But this is known to work with MacOS - https://github.com/freebsd/freebsd-src/tree/main/bin/pwait

**Comment by robinbb** [comment]
Now, pwait does not appear in our codebase.
