### ISSUE TITLE
No strict ledger consistency tier3 regression test

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1263]
We have access to the new [post hard-fork ledger](https://storage.googleapis.com/tmp-hardfork-testing/fork-config-3NLRTfY4kZyJtvaP4dFenDcxfoMfT3uEpkWS913KkeXLtziyVd15.json.gz). 

Verify that our ledger at height `359604` has identical values.

Assertions:
* The number of accounts are equal
* All balance values are identical
* All nonce values are identical

**Comment by trevorbernard** [comment]
This issue is blocked by: https://github.com/Granola-Team/mina-indexer/issues/1264

**Comment by robinbb** [comment]
https://drive.proton.me/urls/Y7TMBBP2JR#mF40IA6J0ptH
