### ISSUE TITLE
Deploy tier3 and prod indexer with `359604` blocks

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1264]
This is so that we can export the ledger at height 359604 to enable a ledger consistency check.

**Comment by trevorbernard** [comment]
Resolved: https://github.com/Granola-Team/mina-indexer/commit/0ed38449ef1ca175388de11867f96707185b3d3d

**Comment by robinbb** [comment]
Will keep this issue open until prod has all the blocks. Still in progress.

**Comment by robinbb** [comment]
Done.
