### ISSUE TITLE
Account creation fee not deducted for newly created accounts in the Balance Sorted Accounts

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1288]
When applying the staged ledger, we need to track newly created accounts to ensure the correct deduction of the account creation fee. It appears only accounts created via InternalCommands are correct.

**Comment by Isaac-DeFrain** [comment]
Do you have an example? I ask because we do take account creation fees into account for the balance-sorted calculations

**Comment by robinbb** [comment]
@Isaac-DeFrain My understanding, from Slack conversations with Trevor, is that this is systematically wrong - an off-by-1 error that appears everywhere.

**Comment by trevorbernard** [comment]
> Do you have an example? I ask because we do take account creation fees into account for the balance-sorted calculations

20652.221264443
