### ISSUE TITLE
Balance discrepancy of 719 Mina for public key `B62qqa9g4CFfkSuX2j22S52z6UfcDcS9tMTgQrFKZ21v7GrEP6Zu5Tc`

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1292]
At block height `359604`, there is a balance discrepancy of 719 Mina for the specified public key. This discrepancy corresponds to the coinbase reward minus the account creation fee.

I suspect this discrepancy is visible at block height 2.

**Comment by trevorbernard** [comment]
The Indexer's ledger has the account balance at: 114346.520102957 where as the mainnet state dump has it at 113627.520102957. We have 719 more Mina.

**Comment by Isaac-DeFrain** [comment]
Still a problem?

**Comment by trevorbernard** [comment]
I suspect it is but we won't know for sure until we have the ledger export at height 359604 from the prod indexer.

**Comment by trevorbernard** [comment]
This is still a problem. I asked Gareth and Jon Washburn for some help.
