### ISSUE TITLE
GraphQL transactions return results in Inconsistent order

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1293]
The GraphQL transactions endpoint currently returns results in an inconsistent order. For transactions within a given block height, the results should follow a consistent order based on the specified `blockheight_asc|desc` parameter and should be sorted by nonce within each block height.

We should support ordering by nonce asc|desc.

```graphql
query TransactionsNonceIssue {
  transactions(query: {canonical: true, from: "B62qospDjUj43x2yMKiNehojWWRUsE1wpdUDVpfxH8V3n5Y1QgJKFfw"}) {
    nonce
    blockHeight
  }  
}
```

**Comment by robinbb** [comment]
Suggesting that @Isaac-DeFrain look into this, as this is likely due to the use of hash maps that do not preserve order.
