### ISSUE TITLE
Inability to distinguish genesis ledger accounts from post genesis accounts from GQL

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1305]
There is currently no method to determine if an account was part of the genesis ledger or created afterwards. This distinction is crucial because accounts created after the genesis ledger incur a 1 Mina account creation fee. This would be useful to the frontend to show that a 1 Mina creation fee was incurred to create the account. This feature exists in MinaExplorer.

**Comment by n1tranquilla** [comment]
#1308 does not have a test for the genesis_ledger property, nor can I find this property in the explorer. Reopening. 
<img width="2032" alt="Screen Shot 2024-07-22 at 10 17 07 AM" src="https://github.com/user-attachments/assets/f1b9e5b4-158c-4d50-909b-d1e3e582c594">
