### ISSUE TITLE
Embed full best ledger in db

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1313]
We currently only track account balances. Track full `Account` instead.

**Comment by Isaac-DeFrain** [comment]
Related #1291

**Comment by robinbb** [comment]
Without this, we crash on certain queries (e.g. https://minasearch.com/addresses/accounts/B62qrQiw9JhUumq457sMxicgQ94Z1WD9JChzJu19kBE8Szb5T8tcUAC/commands/user)
