### ISSUE TITLE
Nonces in transactions are indexed from zero but should return the nonce count to avoid off-by-one errors

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1317]
Nonces in transactions are being displayed starting from zero, while the ledger counts nonces from one. This discrepancy leads to many nonces in the ledger being off by one.

Though there are nonces that are accurate. Likely from the genesis ledger.

**Comment by robinbb** [comment]
Should an account that is created by way of a user command (balance transfer or payment, say) have a nonce of 0 or a nonce of 1?

**Comment by robinbb** [comment]
@trevorbernard I have sent you a more recent ledger dump. Please have a look to see if recent changes by Isaac have created the appropriate changes for nonces.

**Comment by trevorbernard** [comment]
> Should an account that is created by way of a user command (balance transfer or payment, say) have a nonce of 0 or a nonce of 1?

If the account gets created from someone sending you Mina, the nonce of the newly created account technically doesn't exist yet. Only when you send a transaction will the 0 nonce be used

**Comment by trevorbernard** [comment]
> @trevorbernard I have sent you a more recent ledger dump. Please have a look to see if recent changes by Isaac have created the appropriate changes for nonces.

The nonce issue still persists

**Comment by Isaac-DeFrain** [comment]
So nonces are optional?

**Comment by trevorbernard** [comment]
> So nonces are optional?

I wouldn't call it optional. I would describe as "Uninitialized". But I could see how we would make it `Option<Nonce>` in the `Account` to track the uninitialized state. Just like how we do with parsing the genesis ledger

**Comment by Isaac-DeFrain** [comment]
We put a zero nonce for genesis ledger accounts
