### ISSUE TITLE
PR template for DB version bump

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1330]
Add a checkbox reminder for reviewers to increment the DB version when we've either modified a RocksDB (composite) key or value.

**Comment by Isaac-DeFrain** [comment]
Basically I want a just recipe to add to my git pre-commit hook that simply notifies me when I commit changes to any file that alters the data or the database itself

**Comment by Isaac-DeFrain** [comment]
More files/directories probably need to be watched

**Comment by trevorbernard** [comment]
This is done
