### ISSUE TITLE
The GraphQL Fee Transfer endpoint isn't correctly filtering by recipient B62qmB7U9eVkrn8GPFnuKru4hMptrVQVxi9iKcVoeE5zqJWYYw8aZ4C

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1350]
In the internal commands listing page, add the following PK `B62qmB7U9eVkrn8GPFnuKru4hMptrVQVxi9iKcVoeE5zqJWYYw8aZ4C` in the recipient column filter and it will display an incorrect result.

**Comment by n1tranquilla** [comment]
what should it look like?

**Comment by n1tranquilla** [comment]
Results are the same on minaexplorer.com vs minasearch.com. I'm closing
