### ISSUE TITLE
`StakesLedgerAccountWithMeta` does not support various stats required for staking leaderboard

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1356]
Missing stats (per epoch):

- [x] number of blocks produced 
- [x] number of supercharged blocks produced 
- [x] number of slots produced
- [x] orphan rate

**Comment by Isaac-DeFrain** [comment]
number of blocks produced per epoch -> `BlockStore::get_block_production_epoch_count`

**Comment by Isaac-DeFrain** [comment]
number of blocks produced per epoch => `StakesLedgerAccountWithMeta { epoch_num_blocks, .. }`
