### ISSUE TITLE
Indexer incorrectly claims a user command is part of a block

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1409]
Our tests assert that `mainnet-220897-3NL4HLb7MQrxmAqVw8D4vEXCj2tdT8zgP9DFWGRoDxP72b4wxyUw.json` contains a user command whose recipient is `B62qkCALyHkUGBTvLSc35GTmF5wzYEiXGLMDA2rBMDH2AruHxgcxSjg`. 

This assertion is coded into our tests here: https://github.com/Granola-Team/mina-indexer/blob/bbb4872b69509871dcac28a2d62d57eb202ab7bc/rust/tests/command/store.rs#L82

log out the Vec<SignedCommands> from the assertion and you will find that the `indexer_store` includes an extra user command that the block does not include.

**Comment by robinbb** [comment]
@n1tranquilla Good find. Are you working on a fix, too? Should you be assigned this issue?

**Comment by n1tranquilla** [comment]
not an issue on main
