### ISSUE TITLE
Indexer stores a parsed JSON represention of the block, instead of raw file. 

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1424]
Block ingestion takes a long time, in part because the indexer parses the block first, and then stores the parsed file in rocksdb. 

RocksDb could simply store the raw json, provided we adjusted our representation of a block in the database.

**Comment by robinbb** [comment]
... but then we would have to access the block using its native representation, which is perhaps less efficient and less useful than our parsed version?

Note that *reading* a block from disk is expensive, but *parsing* a read block is not.

**Comment by n1tranquilla** [comment]
I examined both. We add some data like height, network, and state hash. But the contents are otherwise the same.

**Comment by Isaac-DeFrain** [comment]
Related to #1545

**Comment by jhult** [comment]
Relates to #1520. Closing.
