### ISSUE TITLE
Only use async runtime for the webserver and unix domain socket handler

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#1438]
Isolate the async runtime to the things that need it. Ingestion should not use async as it simply adds overhead to I/O. Intermixing blocking IO with async IO can be problematic. You must use the async runtimes I/O otherwise you'll block the underlying thread until the I/O is finished. Async fns are basically futures then can be paused and resumed. 

Here is an example:

```rust
pub fn start_web_server(addrs: impl net::ToSocketAddrs) -> anyhow::Result<()> {
    let runtime = Runtime::new().expect("Tokio Runtime exists");
    let _ = runtime.block_on(async {
        HttpServer::new(move || {
            App::new()
                .service(transactions::get_transaction)
                .wrap(Cors::permissive())
        })
        .bind(addrs)?
        .run()
        .await
    });
    Ok(())
}

```

**Comment by jhult** [comment]
We are going to pause on this and instead create new issues to tackle starting the socket and web server separately from ingestion.
