### ISSUE TITLE
Add GraphQL endpoints for SNARKs analytics page

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#1506]
## Stats
- `Total Snarks Included` - The total number of snarks included in the canonical chain
- `Total Snark Fees Earned` - The total fees earned by canonical snarks
- `Snarks purchased greater than 0` - Number of snarks purchased on canonical chain with a fee greater than 0
- `Number of Snark Workers` - Number of snark producers who have had at least one snark purchased

## Charts

<img width="685" alt="image" src="https://github.com/user-attachments/assets/d04eb547-340b-4d9b-9732-31adbeb59029">

<img width="585" alt="image" src="https://github.com/user-attachments/assets/eb316708-ac62-4c8d-bc71-85cf84776d56">

## Tables

<img width="1334" alt="image" src="https://github.com/user-attachments/assets/99acf247-4684-44ed-96d2-b1cdfeffe638">

`Most Expensive Snark Work` also includes `Block State Hash` column

## Filters

- Date
- SNARK Worker (Public Key)
- Fee (nanomina)

These apply to everything above but not sure that makes sense. I would probably only apply it to the Tables and maybe Charts 

---

This issue blocks https://github.com/Granola-Team/mina-block-explorer/issues/987

Equivalent ME page: https://minaexplorer.com/analytics/snarks

**Comment by n1tranquilla** [comment]
I need to go through analytics in general and determine what information is important to have in our GraphQL endpoints.

**Comment by n1tranquilla** [comment]
Snarks per day & average snark fees exist as a single chart on https://minasearch.com/analytics/snarks?limit=1000

Total snark fees earned, top snarkers, and most expensive snark work will be covered by #794 issue, which display those stats per public key.
