### ISSUE TITLE
New endpoint (REST or GQL) to support top stakers board per epoch

### ISSUE THREAD

**Issue by nathan-tranquilla** [Granola-Team/mina-indexer#1533]
We need an REST/GQL endpoint to support a list of top stakers **per epoch** with a default sort of canoncal blocks descending. Each staker will have the following properties per epoch:
* username
* public key
* canonical blocks produced
* supercharged blocks produced
* slots produced
* orphan rate
* % of blocks produced

Suggested design:

```
GET /top-stakers?epoch=1&sort=CANONICAL_BLOCKS_DESC

Response Body (200):
[
   {
      "username": <String>,
      "public_key": <String>,
      "canonical_blocks_produced": <Number>,
      "supercharged_blocks_produced": <Number>,
      "slots_produced": <Number>,
      "orphan_rate": <String>,
      "percent_of_blocks_produced": <String>
   }
]
```

Considered done when REST endpoint has the following:
[ ] default sort is canonical blocks desc
[ ] epoch is URL parameter
[ ] array of results returned corresponding to stats per epoch per producer

![Image](https://github.com/user-attachments/assets/a60e5229-a233-413a-bf61-4d8bd763010b)

**Comment by n1tranquilla** [comment]
blocks: https://github.com/Granola-Team/mina-block-explorer/issues/984

**Comment by n1tranquilla** [comment]
Blocks https://github.com/Granola-Team/mina-block-explorer/issues/985

**Comment by Isaac-DeFrain** [comment]
This looks great to me!
From the looks of it, this would require a significant refactor of the `stakes` GQL endpoint. The ultimate goal is to have a (cleaner) `topStakers` endpoint for querying the above data which is currently, awkwardly, located in the `stakes` endpoint

**Comment by n1tranquilla** [comment]
I don't understand why `stakes` would have to be refactored at all. Can't we simply add the REST endpoint, and leave the GQL endpoint as it is?

**Comment by Isaac-DeFrain** [comment]
We certainly can
