### ISSUE TITLE
Create REST endpoint for SNARKers leaderboard

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1534]
Inspiration: https://minaexplorer.com/snark-producers

We need to be able to find out who the top SNARKers are per epoch

Design
```
GET /top-snarkers?epoch=1&sort=TOTAL_FEES_DESC

Response Body (200):
[
  {
     "username": <String>,
     "public_key": <String>,
     "total_fees": <String>,
     "total_snarks_sold": <Number>
     "min_fee": <String>,
     "max_fee": <String>
  }
]
```

This issue is considered done when
[ ] stats per epoch via url parameter
[ ] default sort is total fees descending
[ ] sort parameter in URL works and support 
  * total fees desc
  * highest fee desc
 
[ ] each rows corresponds to the stats per epoch per public key

**Comment by Isaac-DeFrain** [comment]
This also looks great!
Similar idea to the `topStakers` endpoint (#1533) to achieve a similar goal.
