### ISSUE TITLE
By default, `just deploy-local-prod` should ingest all blocks

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1548]
This is currently breaking front-end tests against the locally running indexer in CI.

TODO:

* add optional parameter to `deploy-local-prod` to not ingest blocks
* update buildkite steps to use 'n' parameter in tier2/3

**Comment by jhult** [comment]
I believe this should be reopened since this was reverted: https://github.com/Granola-Team/mina-indexer/commit/609f060b1a37f4b549769ee6714e646f5c4e42ce

**Comment by n1tranquilla** [comment]
Done.
