### ISSUE TITLE
Jonathan to ensure branches are merged with Mina codebase

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1580]

**Comment by trevorbernard** [comment]
@n1tranquilla This shouldn't be an issue in the `mina-indexer`. This is a task for @jhult and not a problem with the indexer.

**Comment by n1tranquilla** [comment]
I have no memory of making this issue. 

https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXQ4eWRyY20xNTYybGlrOXJ0cjFwcm90aTVhNWpvNWtucWNlMXN2ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/FPjbHO0jJxGsE/giphy.gif
