### ISSUE TITLE
Deploy all blocks to prod

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1581]

**Comment by Isaac-DeFrain** [comment]
Do we want to block this on #1548 or simply remove the `--do-not-ingest-orphan-blocks` flag? I'd vote for the latter.

**Comment by Isaac-DeFrain** [comment]
I'll remove the flag from the prod deploy script

**Comment by Isaac-DeFrain** [comment]
Done https://github.com/Granola-Team/mina-indexer/commit/1639261e40a2e5643fc8ed6c02400323b930c5d1
