### ISSUE TITLE
Count applied & failed canonical user commands

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1587]
Blocks #1204

**Comment by n1tranquilla** [comment]
Yes, this seems like it would be directly related. But I don't think this is strictly needed for this issue unless this story is dependent upon those counts first.

**Comment by n1tranquilla** [comment]
There are 4 permutations of status and canonicity to be indexed
* applied and canonical
* failed and canonical
* applied and non-canonical
* failed and non-canonical
