### ISSUE TITLE
Only persist blocks to rocksdb that are behind the transition frontier

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#1593]
Blocks within the transition frontier are in a constant state of flux. It might be better to hold the latest 270 blocks in memory and determine their characteristics on the fly.

Considerations:
* Would re-orgs still be necessary?
* Canonicity is emergent (dynamic) within the frontier, so this may make more sense not to write to DB yet.
* GraphQL layer might have to combine in-memory + database to return full set of data.
* Holding 270++ blocks in memory likely ok as the dataset is not too large.

**Comment by n1tranquilla** [comment]
I realize this represents a lot of changes and so i've placed it in wishful for now.

**Comment by trevorbernard** [comment]
What is the problem this issue aims to solve? Is it updating the persistent view in the face of a re-org? Because it's unclear to me.

**Comment by Isaac-DeFrain** [comment]
This is more or less the domain of the witness tree. The only difference being that we update the data in the db when we ingest the block. I think we are doing it the right way currently.

Keep in mind that this would be a very significant amount of work to implement, only to be a potential benefit during the _initial ingestion process_ (which is not the main mode of the indexer). We anticipate most users will either use our FE or download db snapshots from us, not ingest all blocks themselves. However, even if they do, the initial ingestion process takes ~10 hours, whereas the indexer will be in its primary "watch" mode indefinitely.

Closing.
