### ISSUE TITLE
Get previous post-hardfork staking ledgers

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1617]
We need all staking ledgers for the post-hardfork network

**Comment by jhult** [comment]
https://staking-ledgers.minasearch.com

**Comment by jhult** [comment]
Example: https://staking-ledgers.minasearch.com/mainnet-7-jxQgtuyHp8nA2P6F9CSRrLcVeHi8Ap7wVHeNnH2UbSX15izcSHK.json
