### ISSUE TITLE
Get the hardfork genesis block

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#1618]

**Comment by jhult** [comment]
https://storage.googleapis.com/mina_network_block_data/mainnet-359905-3NL3txaSjP8Snfy7w1EJhLLH1KeBGX3P1Q2FZ9qDtAsq2dk72obK.json

**Comment by Isaac-DeFrain** [comment]
That's not it, it isn't in the google bucket. The hardfork genesis block has state hash `3NK4BpDSekaqsG6tx8Nse2zJchRft2JpnbvMiog55WCr5xJZaKeP`.

**Comment by Isaac-DeFrain** [comment]
Also, the hardfork genesis block should have height 359605.

**Comment by Isaac-DeFrain** [comment]
It may be possible to work around this having the full PCB. I'll have to think about it more.
