### ISSUE TITLE
Save State Client Response

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#170]
When running the `save-state` client command, the client always receives back an error, even when the snapshot is created successfully. Fix this so that the `save-state` command reports its success as well as a summary of its result

**Comment by trevorbernard** [comment]
The problem is that the `mina-indexer client` expects a serialized version of the response but it's returning a string. I will close this issue when the following PR gets merged: https://github.com/Granola-Team/mina-indexer/pull/218

**Comment by trevorbernard** [comment]
This issue disappear when we removed the save snapshot feature
