### ISSUE TITLE
Chain Canonicity functionality does not respect `canonical_threshold` CLI Argument

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#171]
when running the `mina-indexer`, one can pass in a flag `canonical_threshold` that should determine how many blocks after (confirmations) from the current Best Tip to consider as a Canonical block. Currently, the indexer does not respect this flag, and simply uses a constant `CANONICAL_UPDATE_THRESHOLD` defined in `src/lib.rs`. Fix will include removing this constant from all code excepting as a default in the `clap` command line parser.

**Comment by Isaac-DeFrain** [comment]
This isn't a bug. The `canonical_update_threshold` pertains to how often the `canonical_tip` is updated in the witness tree, not how many confirmations determine a block's canonicity. A cli arg could also be added for this, but `canonical_update_threshold` is not it.

**Comment by Isaac-DeFrain** [comment]
I see, you're asking for another cli arg. On it!

**Comment by robinbb** [comment]
Requires tests that pass in CI to show completion. Re-opening.
