### ISSUE TITLE
CLI Displays Floating Point instead of NanoMina

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#172]
Currently, the formatting for displaying account balances in the `mina-indexer` client uses a floating point representation. Change this to use NanoMina in any output that is designed to be consumed by another program, to prevent rounding errors.

<hr>

Asana Tasks referenced:
* https://app.asana.com/0/1203669416123378/1205103570662676/f

**Comment by jstavh** [comment]
Hey @jenr24G - we ran the `mina-indexer client` testing 4 public keys and not seeing a floating point representation. Here is the output of some public keys we have tested:
 
```$ RUST_BACKTRACE=1 target/release/mina-indexer client account -p "B62qp8dFx9w5si4QzcPdMmSqFd55MPgNJiAsxtsYCzRYLGvV4XDHXXu"
{
  pk:       B62qp8dFx9w5si4QzcPdMmSqFd55MPgNJiAsxtsYCzRYLGvV4XDHXXu
  balance:  5000000000000
  nonce:    0
  delegate: B62qp4Gwy1ZxVA6EhqFPJ7oZphYKhuJYgVdYNkBUQEmwhY2J7d311Ys
}
$ RUST_BACKTRACE=1 target/release/mina-indexer client account -p "B62qrzeAiJZQ4DnFaiDypcprKpXgV4vac8PrmP4rotUHRz5U4JbTy1E"
{
  pk:       B62qrzeAiJZQ4DnFaiDypcprKpXgV4vac8PrmP4rotUHRz5U4JbTy1E
  balance:  0
  nonce:    0
  delegate: B62qrzeAiJZQ4DnFaiDypcprKpXgV4vac8PrmP4rotUHRz5U4JbTy1E
}
$ RUST_BACKTRACE=1 target/release/mina-indexer client account -p "B62qqMo7X8i2NnMxrtKf3PAWfbEADk4V1ojWhGeH6Gvye9hrMjBiZjM"
{
  pk:       B62qqMo7X8i2NnMxrtKf3PAWfbEADk4V1ojWhGeH6Gvye9hrMjBiZjM
  balance:  32576416881266
  nonce:    0
  delegate: B62qpge4uMq4Vv5Rvc8Gw9qSquUYd6xoW1pz7HQkMSHm6h1o7pvLPAN
}

**Comment by jenr24G** [comment]
Hey, you're right! This isn't actually an issue, I'm getting the same result! Nice catch!

**Comment by jenr24G** [comment]
I believe we want our human-readable displays to output regular mina, but anything consumed by an API should use nanomina. better yet we should just give the client a flag to choose
