### ISSUE TITLE
`TransactionStore` interface does not conform to common interface defined by `BlockStore` and `CanonicityStore` `impl`s

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#174]
The `TransactionStore` implementation does not use the common interface described by the `BlockStore` and `CanonicityStore` implementations. Fix will include removing `TransactionKey` `struct` and `impl` and creating a `TransactionStore` `trait` with an implementation in `src/store.rs`

**Comment by trevorbernard** [comment]
Won't fix. There will be an over-haul on how we manage our data access. It will be address there.

**Comment by robinbb** [comment]
If this issue were recast as a problem statement, it might be reasonable to retain it.
