### ISSUE TITLE
Problem: Cannot send event from file system watcher: sending into a full channel

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#202]
Investigate file watcher error and improve handling

**Comment by trevorbernard** [comment]
Use a more realistic size that is divisible by 2.

**Comment by robinbb** [comment]
@trevorbernard Can you say more about what this is about? Is it related to our ability to process large log (block) directories?

**Comment by robinbb** [comment]
I think that this is resolved. Closing.
