### ISSUE TITLE
Add nix best practices so it doesn't break hermeticity

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#203]
There have been on occasion instances where modifying the Cargo.toml broke hermeticity in the nix build

**Comment by jenr24** [comment]
This is a tough one because Cargo manages dependency versions itself, and only delegates to nix through the `Cargo.lock`

**Comment by trevorbernard** [comment]
We've eliminated the mina-rs submodule dependency. That was the primary cause of breaking hermeticity in our nix builds.

**Comment by trevorbernard** [comment]
Closing because of previous comment
