### ISSUE TITLE
Create new state from non-genesis ledger and block

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#210]
Currently, we can create an indexer state from genesis with an optional ledger.
I propose we provide three ways to create an indexer state:
`new(root_hash, genesis_ledger, blocks_path)` create a state from genesis state hash and ledger
`new_non_genesis(precomputed_block, ledger, blocks_path)` create a state from a non-genesis precomputed block and ledger
`new_testing(precomputed_block, ledger, blocks_path)` create a state from a block, optional ledger, and optional block store. This would only be for use in tests.
With this, we could also remove the Option from the root_branch

**Comment by trevorbernard** [comment]
We should have a discussion what problem this aims to solve. It also might fall victim to bitrot since the BlockParser is going to change dramatically. Putting on hold.

**Comment by Isaac-DeFrain** [comment]
removed
