### ISSUE TITLE
Problem: Witness tree and datastore highly coupled

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#215]
## Problem:

The witness tree is highly tightly coupled to the persistent datastore. 

## Proposed Solution

Disentangle the witness tree logic from the database code. The goal for canonical chain discovery should be accept a stream of block added events and emit it's own lifecycle events. E.g. CanonicalChainExtended(state_hash), CanonicalChainReorg(height, Vec<StateHash>), etc.

**Comment by jenr24G** [comment]
Working on a solution to this issue, would be interested in further discussion
