### ISSUE TITLE
Add indexer specification to the codebase

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#216]
Provide documentation to the design of the indexer so that people can more easily understand how to contribute

**Comment by jenr24** [comment]
I can start documenting what is there, though it will end up overwritten when we refactor the state module

**Comment by trevorbernard** [comment]
@jenr24 maybe it's best we wait

**Comment by robinbb** [comment]
No need for a "spec", though documentation is desirable. We have other issues for that. Closing.
