### ISSUE TITLE
Problem: There is no documentation for the client/server communication protocol

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#222]
Create a specification document that describes the `mina-indexer` client server protocol. Create `ebnf` grammar for the protocol.

**Comment by trevorbernard** [comment]
The benefit of this is that a 3rd party processes may use the UDS API to create their own applications

**Comment by robinbb** [comment]
I prefer to close this as "won't do", and leave GraphQL as the supported way to interact with the server (with HTTP REST secondarily supported).
