### ISSUE TITLE
Problem: Run Phase not visible to Client

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#233]
The `MinaIndexer` object has access to a state variable that represents the current phase of the indexer: Intialization, Watching for Blocks, Opening an IPC connection, etc. However, this information is not available to the Indexer Client. Solution will add a new field to the `SummaryVerbose` and/or `SummaryShort` records so that this data is accesible to the client.

**Comment by jenr24G** [comment]
about to fix!

**Comment by trevorbernard** [comment]
Closing as indexer run phase was removed
