### ISSUE TITLE
Problem: Have to run all regression tests every time

### ISSUE THREAD

**Issue by jenr24G** [Granola-Team/mina-indexer#244]
Whenever one wants to add a new feature or fix a bug, one needs to write a regression test demonstrating the feature or bugfix working; however, when writing these tests, all other tests in the suite must be run in order before the new test can be ran. As the regression suite grows, this will bottleneck the development feedback loop's velocity. A fix would involve either caching passing tests, or allowing a developer to run only a subset from their local environment

**Comment by trevorbernard** [comment]
A possible solution is to add test runner functionality to execute specific test targets for the regression suite

**Comment by trevorbernard** [comment]
Resolved in the following PR: https://github.com/Granola-Team/mina-indexer/pull/245
