### ISSUE TITLE
Problem: Wait too long for librocksdb to compile too often

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#248]
This is slowing down the feedback loop. We should cache the compiled `librocksdb` or add the dependency to our nix flake.

**Comment by trevorbernard** [comment]
Cargo has a built in tool to visualize build timings.
```
cargo build --timings
```
It definitely is the culprit. It also shows various scripts like zstd-sys, l4s-sys, bzip2-sys taking a bunch of time and we don't use the features. An improvement might be to not include those in the build.

**Comment by jenr24** [comment]
these are all native library wrapper crates. i'll take a look at their `build.rs` scripts to see if we can statically link the libraries using nix

**Comment by Isaac-DeFrain** [comment]
This doesn't seem to be an issue anymore. Closing for now.
