### ISSUE TITLE
Problem: Ctrl-C does not properly kill the indexer process

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#249]
A manual `kill` of the indexer's PID is required. This should be handled by ctrl-c.

**Comment by jenr24** [comment]
I thought we fixed this with the `ctrl-c` crate. Maybe we need better signal handling?

**Comment by trevorbernard** [comment]
Currently we `std::process::exit(1337)`. We should have a proper shutdown mechanism so we can *cleanly* shutdown when we trap a sigkill or shutdown command
