### ISSUE TITLE
Problem: there is no clean shutdown sequence for the indexer

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#255]
Add the necessary hooks and methods to cleanly shut down the Mina Indexer. Things to consider: Indexer state, rocksdb, graphql webserver, UDS/IPC socket files, etc.

**Comment by trevorbernard** [comment]
This needs to be done before adding a regression test. https://github.com/Granola-Team/mina-indexer/issues/419

**Comment by Isaac-DeFrain** [comment]
Didn't you do this @trevorbernard?

**Comment by trevorbernard** [comment]
I added a shutdown with process exit. What we need to do is signal the the DB to shutdown cleanly. I've been thinking about 2 different approaches. 

1. We send include a "management" channel in the pipeline use a pattern like this.

```rust
tokio::select! {
  shutdown_future => {
    break;
  }
}
```

**Comment by robinbb** [comment]
@trevorbernard Possible to explain to @jhult how to accomplish "doneness" for this issue?

**Comment by robinbb** [comment]
@trevorbernard This has become urgent because the lack of clean shutdown threatens to clog up the CI machines (I am manually killing processes, as-is). Too many mina-indexer processes remain running, and then "too many open files" becomes a problem, not to mention RAM consumption.

**Comment by trevorbernard** [comment]
Ok, this will be the next issue I tackle

**Comment by robinbb** [comment]
@trevorbernard This is less urgent because the existing shutdown sequence seems to suffice to un-break the CI. Decreasing priority.
