### ISSUE TITLE
Decouple our domain objects from `mina-rs` serialization types for mainnet

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#265]
This coupling isn't ideal if we want to support `berkeley` and the hard fork. I propose we create our own domain objects and add a conversion from mina-rs serialiation types to our own domain objects. This enables us to create conversions for the berkeley precomputed blocks and other sources of blocks like `ExternalTransitions`.

This also enables us to replace mina-rs serialization with our own hermetic serialization implementation.

**Comment by robinbb** [comment]
@trevorbernard @jhult Is this now done, at least to a degree necessary to close this issue?

**Comment by jhult** [comment]
There is still cleanup to combine any duplicate `struct`s. I will work on this.

**Comment by Isaac-DeFrain** [comment]
Blocked by
- [ ] #1596
- [ ] #1597
- [ ] #1598
- [ ] #1599

**Comment by Isaac-DeFrain** [comment]
This issue is not well-defined. On one hand, it's in the "Berkeley Support" milestone. On the other, it's about our OG mainnet serialization types. Closing.
