### ISSUE TITLE
Problem: downloading from Google buckets is not allowed from everywhere

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#267]
This causes a failure in our regression test suite ('./test' file) when `gsutil` runs. The error is:
```
ServiceException: 401 We're sorry, but this service is not available in your location
CommandException: 1 file/object could not be transferred.
```

Probably, we must maintain our own repo of files, cloned from the bucket from which that 'gsutil' command was originally pulling.

**Comment by trevorbernard** [comment]
With the `gsutil` you can rsync to a s3 bucket. https://cloud.google.com/storage/docs/gsutil/commands/rsync

**Comment by robinbb** [comment]
No longer do we download from a Google bucket.
