### ISSUE TITLE
Problem: the regression suite requires a cargo debug build to already exist for it to run

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#273]
Add cargo build back to the regression suite

**Comment by trevorbernard** [comment]
@robinbb is there a reason why you removed the `cargo build` in this PR? https://github.com/Granola-Team/mina-indexer/pull/270

**Comment by robinbb** [comment]
I had assumed it was a mistake. Doing the tests also does a build? Is this what we want? If yes, we would want to delete the build step in the CI. I am habituated to build pipelines that have separate build-and-test steps, though indeed the test step often prereqs the build step. In other words, the 'just' tool should require the 'build' step before running 'test-regression'... and it does already do that, meaning that 'cargo build' would run twice, the second time unnecessarily, if it were put back into the regression suite. In other words, if you simply invoke 'just test-regression', the right things happen.

**Comment by trevorbernard** [comment]
Ok, thanks for clarifying. It's not an issue. Closing.
