### ISSUE TITLE
Do not rely on `mina-rs` primitives to hash transaction

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#279]
In an effort to disassociate our codebase from `mina-rs`, implement the transaction hash algorithm in our codebase in a hermetic way.

**Comment by robinbb** [comment]
@trevorbernard @jhult Is this now done?

**Comment by robinbb** [comment]
@trevorbernard @jhult Just looking for status on this.

**Comment by jhult** [comment]
Relates to #265

**Comment by n1tranquilla** [comment]
I think this is wishful. It's not strictly necessary and the case for fixing it has not been made in a way that convinces me that this is a true backlog item.

**Comment by trevorbernard** [comment]
it is necessary if you want to remove `mina-rs`

**Comment by Isaac-DeFrain** [comment]
At the very least, we need `bin_prot` support
