### ISSUE TITLE
Problem: the `mina-rs` package has dependencies that are severe security risks

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#288]
... yet we don't really need mina-rs.

**Comment by sunfishcode** [comment]
According to mina-indexer's checked in Cargo.lock, mina-indexer depends on `rustix` via `tempfile` and `which`. I have audited both of those libraries and neither use `rustix::fs::Dir` anywhere. So, mina-indexer is unaffected by [GHSA-c827-hfw6-qwvm](https://github.com/bytecodealliance/rustix/security/advisories/GHSA-c827-hfw6-qwvm).

**Comment by trevorbernard** [comment]
Even though we weren't affected, an update to the dependencies resolved this issue. Closing https://github.com/Granola-Team/mina-indexer/pull/289

**Comment by robinbb** [comment]
Appreciate that audit, @sunfishcode.
