### ISSUE TITLE
Problem: `is_valid_block_file` can return false positives

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#323]
Support only these two patterns explicitly:

```rust
// <network>-<block_height>-<state_hash>.json
// <network>-<state_hash>.json
```
Ensure block_height is a u64, the extension is `json` and the file_name matches the pattern

**Comment by trevorbernard** [comment]
This would be a excellent candidate for creating a property based test

**Comment by Isaac-DeFrain** [comment]
Blockchain_length should be `u32`
