### ISSUE TITLE
Problem: We're missing the genesis block in the indexer

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#341]
Understand how the genesis block gets created so we may do the same in the indexer. The precomputed block bucket `min(block_height) == 2`. It's likely the case there is an (semi-) automated way to generate the block from the genesis ledger. 

You can query the node (GQL) and get the genesis block. It exists in the AN and MinaExplorer.

**Comment by trevorbernard** [comment]
> So, the precomputed block bucket does not include the genesis block, you're saying, @trevorbernard ?

@robinbb It's not included as a precomputed block but it does exist. The genesis block is generated from the node configuration (aka genesis ledger, etc.) at startup from my understanding. It's effectively a no-op block. I pinged a few people from MF/O1 and they pointed me in the right direction

**Comment by Isaac-DeFrain** [comment]
What does the previous state hash of the genesis block mean (3NLoKn22eMnyQ7rxh5pxB6vBA3XhSAhhrf7akdqS6HbAKD14Dh1d)?

**Comment by Isaac-DeFrain** [comment]
Strange that MinaExplorer says 720 coinbase but the others say 0...

**Comment by trevorbernard** [comment]
We have a reference implementation in `mina-rs`

https://github.com/ChainSafe/mina-rs/blob/8f3f41ca6bfaadf898baa75a4849295177f26aaf/consensus/src/genesis/genesis_impl.rs#L13

https://github.com/MinaProtocol/mina/tree/develop/docs/specs/consensus#611-genesis-block
