### ISSUE TITLE
Problem: `mina-rs` project is unmaintained but we rely on the `mainnet` block parsing code

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#342]
Create hermetic parsing code that replaces the `mina-serialization` module in `mina-rs`

**Comment by Isaac-DeFrain** [comment]
@jhult will take over

**Comment by Isaac-DeFrain** [comment]
- `src/mina_blocks/v1` has all the block (de)serializer bits
- we will need to implement their `version` lib to use for transaction hashing (one can see what a versioned block looks like by using `mina-indexer best-tip -v` or any other verbose block query)
- a lot of our internal structs use mina-rs structs but should only required a mechanical change to use ours
