### ISSUE TITLE
Question: Will there be an API that will be compatible with o1js?

### ISSUE THREAD

**Issue by FilipHarald** [Granola-Team/mina-indexer#355]
Awesome project and very nice to get an overview of the architecture in the docs, thank you. If this is the wrong forum to ask questions, I'm sorry, please refer me elsewhere.

In the "About" you write that this is a "re-design of the Mina Archive Node". And I'm trying to figure out how many of the features that this implementation will support. I can see that you have the Rosetta API, [I'm guessing that will be compatible with this?](https://docs.minaprotocol.com/node-operators/rosetta).

But I'm also wondering if you will have an API that will work out of the box with `o1js`? So that your indexer can be used as `archive` directly, [like documented here](https://docs.minaprotocol.com/zkapps/o1js/fetch-events-and-actions#using-the-archive-node-with-o1js).

**Comment by trevorbernard** [comment]
Hi @FilipHarald, thanks for your interest in the Mina Indexer. This is the right place to ask such questions.

> And I'm trying to figure out how many of the features that this implementation will support. 

The Indexer is meant to be a superset of the data that the Archive Node provides eventually supporting pre and post hard-fork chains. We aim to be schema compatible with the Mina Explorer GraphQL API for `mainnet` and provide an GQL API for `berkeley`.


> I can see that you have the Rosetta API, [I'm guessing that will be compatible with this?](https://docs.minaprotocol.com/node-operators/rosetta).

Yup, that is correct.

> But I'm also wondering if you will have an API that will work out of the box with o1js? So that your indexer can be used as archive directly, [like documented here](https://docs.minaprotocol.com/zkapps/o1js/fetch-events-and-actions#using-the-archive-node-with-o1js).

That is our intent. I'll create an issue to explicitly track this request.

**Comment by FilipHarald** [comment]
@trevorbernard thank you for your swift reply. I will keep my eyes on #357 .

**Comment by robinbb** [comment]
Note https://github.com/Granola-Team/mina-indexer/issues/735

**Comment by robinbb** [comment]
See also #957
