### ISSUE TITLE
Problem: unable to build with `nix build '.?submodules=1'`

### ISSUE THREAD

**Issue by FilipHarald** [Granola-Team/mina-indexer#356]
I'm trying to build the project but I get an error for source dependencies. I paste the command with error below. I have already tried the following commands, and they are working without errors.

- `nix develop '.?submodules=1'`
- `nix-shell --run "just test-unit"`
- `nix-shell --run "just test-regression"`

```bash
$ nix build '.?submodules=1'
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/7yf4zdfi98yd4f5rs2bl7fa8zk96hx0q-mina-indexer-0.1.1.drv' failed with exit code 101;
       last 10 log lines:
       >   failed to load source for dependency `bin-prot`
       >
       > Caused by:
       >   Unable to update /build/02i62gm0bi32cxrqx28jwy77h78hn7m9-source/mina-rs/protocol/bin-prot
       >
       > Caused by:
       >   failed to read `/build/02i62gm0bi32cxrqx28jwy77h78hn7m9-source/mina-rs/protocol/bin-prot/Cargo.toml`
       >
       > Caused by:
       >   No such file or directory (os error 2)
       For full logs, run 'nix-store -l /nix/store/7yf4zdfi98yd4f5rs2bl7fa8zk96hx0q-mina-indexer-0.1.1.drv'.
```

**Comment by trevorbernard** [comment]
Yes, that is a bug. I suspect it has something to do the first run not having already fetched the submodules. I'll create a bug for this.

**Comment by FilipHarald** [comment]
> Yes, that is a bug. I suspect it has something to do the first run not having already fetched the submodules.

Alright, but do you by that mean that it should work on a second run with `nix build '.?submodules=1'`? Because I do not get that to work either.

**Comment by trevorbernard** [comment]
> > Yes, that is a bug. I suspect it has something to do the first run not having already fetched the submodules.
> 
> Alright, but do you by that mean that it should work on a second run with `nix build '.?submodules=1'`? Because I do not get that to work either.

It's not just the first run but all runs that `nix build '.?submodules=1'` fails. It doesn't appear that the additional `'.?submodules=1'` is being included in the mina-indexer derivation. I'll take some time today to look into this. Like you've discovered, there is a work around.

**Comment by trevorbernard** [comment]
@FilipHarald What version of nix do are you using? Strangely enough, the `nix build '.?submodules=1'` command succeeds on a MBP m1 and Debian 11 using nix version `2.18.1` but when I use `2.19.2` on another Debian 11 machine, it fails with the same error as you. 

I suspect something changed in functionality between `2.18.x` and `2.19.x`

**Comment by Isaac-DeFrain** [comment]
Works for me on Debian 10 using `nix (Nix) 2.13.2`

**Comment by trevorbernard** [comment]
@FilipHarald So after more digging it's a regression introduced in nix `2.19.0`. You can read about it here: https://github.com/NixOS/nix/issues/9530

The work around is to issue the following command:

```sh
nix build "git+file://$(pwd)?submodules=1"
```

I'll add a note in the README to issue the above warning and workaround.

**Comment by jhult** [comment]
FYI, I seemed to bump into this issue with Nix 2.20.1. I downgraded to Nix 2.19.3 and am not hitting this error (bumped into something else though).
