### ISSUE TITLE
Problem: Running with `example.config.yaml` produces `Error: missing field `genesis_ledger`

### ISSUE THREAD

**Issue by FilipHarald** [Granola-Team/mina-indexer#359]
As stated in the title I'm trying to run it with the provided example-config. (I'm only changing the paths to home-directory). I get presented with a missing field error like below. If I add the line `genesis_ledger: ./tests/data/genesis_ledgers/mainnet.json` to the config, it runs without a problem. (I understand that this is not the correct way of doing it though).

```bash
$ ./result/bin/mina-indexer server config --path ./example.config.yaml 
Error: missing field `genesis_ledger`
```

**Comment by Isaac-DeFrain** [comment]
I removed the config file option in favor of cli args. The config file is outdated.
