### ISSUE TITLE
Question: What is the easiest way to start streaming data to the indexer?

### ISSUE THREAD

**Issue by FilipHarald** [Granola-Team/mina-indexer#360]
I struggled to find any documentation about this in the repo. But how do I start listening to the block-data stream? I can find in the Mina-docs that it is [rather a configuration of the mina daemon](https://docs.minaprotocol.com/node-operators/archive-node#set-up-the-archive-node) in order to stream the data.

> 5. Start the mina daemon and connect it to the archive process that you started on port 3086:
```
mina daemon \
    .....
  --archive-address 3086\
```

But I can't see that the mina indexer process exposes any ports?

**Comment by trevorbernard** [comment]
Hi @FilipHarald, we don't need a connection to the mina daemon to get blocks-- we solely rely on processing precomputed blocks.

As part of the startup process, we tell the `mina-indexer` binary to look watch directories for precomputed blocks. Are you on the Mina Protocol discord?

**Comment by FilipHarald** [comment]
@trevorbernard oh I see. Yes I'm "quiq" on their Discord

**Comment by trevorbernard** [comment]
It isn't immediately obvious how to start and run the indexer from the README. https://github.com/Granola-Team/mina-indexer/issues/360

**Comment by FilipHarald** [comment]
@trevorbernard I think you meant this issue? #365

**Comment by trevorbernard** [comment]
> @trevorbernard I think you meant this issue? #365

Yes, you are right!
