### ISSUE TITLE
Update README to provide a quick start guide on how to ingest blocks

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#365]

**Comment by Isaac-DeFrain** [comment]
Do we want to provide instructions for using gsutil and the o1 bucket?

**Comment by trevorbernard** [comment]
I suspect so until we store our own PCBs and have our own block crawler.

**Comment by jhult** [comment]
Relates to #211

**Comment by n1tranquilla** [comment]
I think the README + Justfile is clear enough regarding how to get started. True?

**Comment by n1tranquilla** [comment]
Jonathan and I reviewed the README and we think the average developer can get up and running quickly.
