### ISSUE TITLE
Problem: missing regression test for fetching blocks directly from `gsutil`

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#415]
Allowing `gsutil` to download directly into the `watch_dir` differs from a copying a file directly. `gsutil`. Because of resumable transfers, it first downloads the file in `_.gstmp` suffix before in it's final *.json form. The block ingestion needs to take this into consideration.

**Comment by robinbb** [comment]
Taking.

**Comment by robinbb** [comment]
After speaking with Trevor, I understand that my solution will not address this. Giving up ownership.

**Comment by trevorbernard** [comment]
Actually any regression test that downloads with `gsutil` will satisfy this issue. Closing
