### ISSUE TITLE
Provide a query for SNARKs by work ID

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#431]

**Comment by jhult** [comment]
Related to #693

**Comment by jhult** [comment]
Related to https://github.com/Granola-Team/mina-block-explorer/pull/588

**Comment by jhult** [comment]
@Isaac-DeFrain / @trevorbernard,

Due to https://github.com/Granola-Team/mina-block-explorer/pull/588, is this still required?

**Comment by Isaac-DeFrain** [comment]
It is not. Closing.
