### ISSUE TITLE
Problem: length sort all paths before sync/replay

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#434]

**Comment by trevorbernard** [comment]
The title doesn't adequately describe the problem. What's the actual problem rather than the proposed solution.

**Comment by Isaac-DeFrain** [comment]
While working with a syncing indexer, I noticed that we were length sorting our block paths *before* syncing. This is unnecessary and wrong. We want to sync first, then filter out the paths we've already ingested. Similarly for replay.
