### ISSUE TITLE
Problem: `interprocess` dependency hasn't had a release since November of 2022

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#443]
Interprocess is a library that provides cross platform support for IPC like UDS and Named Pipes but it appears to be not well maintained. Since we don't intend to support the windows platform for servers, remove and replace with the extremely well maintained tokio async library.

**Comment by Isaac-DeFrain** [comment]
We can replace this with `tokio::net::TcpStream`

**Comment by trevorbernard** [comment]
@Isaac-DeFrain I have a branch somewhere where I have a tokio implementation. Remind me and I'll resurrect it if need be.
