### ISSUE TITLE
Problem: we do unnecessary ECC operations while parsing the genesis ledger

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#448]
As an archive process it isn't necessary for us to validate public keys in the genesis ledger with elliptic curve cryptography (ECC). There are 2 known bad public keys in the `mainnet` genesis ledger. Let's continue to ignore them without validating them.

We'll need to remove this in order to eliminate our `mina-rs` dep

**Comment by robinbb** [comment]
Want!

**Comment by trevorbernard** [comment]
Proposed solution: parse as String instead of PublicKeyV1
