### ISSUE TITLE
Add analytics to website

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#474]

**Comment by jhult** [comment]
I believe Google Analytics [is planned to be used](https://github.com/Granola-Team/mina-block-explorer/pull/234), but just in case, here are some alternatives:

- https://github.com/plausible/analytics
- https://github.com/umami-software/umami
- https://github.com/matomo-org/matomo
- https://github.com/PostHog/posthog
- https://github.com/usefathom/fathom

**Comment by jhult** [comment]
Closed via https://github.com/Granola-Team/mina-block-explorer/pull/234
