### ISSUE TITLE
Document required ulimits

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#479]

**Comment by trevorbernard** [comment]
I'm not sure how we're going to test this. We should discuss what behaviour we want the indexer to exhibit when we hit this error. IMHO, I think we should (if possible to) cleanly exit. Then somehow validate that the data isn't half baked.

**Comment by trevorbernard** [comment]
One possible solution is to return a specific error code and we test for that

**Comment by robinbb** [comment]
I propose that we simply document the ulimit (for open files) that is required to run the Indexer.
