### ISSUE TITLE
Problem: `nix` builds are broken on aarch64-darwin

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#481]

**Comment by jhult** [comment]
This is the error I get on an Apple M1:

```
Undefined symbols for architecture arm64:
   "___cxa_end_catch", referenced from:
           std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char>>::overflow(int) in liblibspeedb_sys-2abd140cc78f8689.rlib(perf_context.o)
           std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence[abi:v160006]<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long) in liblibspeedb_sys-2abd140cc78f8689.rlib(perf_context.o)
```

I wonder if [this](https://github.com/speedb-io/speedb/issues/822) could be related.

**Comment by trevorbernard** [comment]
> This is the error I get on an Apple M1:
> 
> ```
> Undefined symbols for architecture arm64:
>    "___cxa_end_catch", referenced from:
>            std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char>>::overflow(int) in liblibspeedb_sys-2abd140cc78f8689.rlib(perf_context.o)
>            std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence[abi:v160006]<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long) in liblibspeedb_sys-2abd140cc78f8689.rlib(perf_context.o)
> ```
> 
> I wonder if [this](https://github.com/speedb-io/speedb/issues/822) could be related.

This is a cmake cross-compilation bug in speedb. The PR linked should resolve your issue

**Comment by trevorbernard** [comment]
If you wanted to learn why it's broke on `aarch64-darwin`, read the following issue which thoroughly describes the problem: (https://github.com/NixOS/nixpkgs/issues/166205). This also explains why our previous flake worked under llvmPackages_11. TIL
