### ISSUE TITLE
Rethink how we log in the indexer

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#485]
We currently hand roll our own file logging/rotation which feels like an anti-pattern. Log management is largely a solved problem on linux systems. There are many popular centralized logging tools at our disposal. In particular, we should use something like `logrotate` to append and rotate log files.

Outcomes:
* Suggestions on logging agents for production systems
* logrotate example configurations
* Removal of hand rolled file logger

**Comment by jhult** [comment]
Do we want to send logs to a centralized location such as [Honeycomb](https://www.honeycomb.io/product-overview)?

If so, we could use something like [Vector](https://vector.dev/) to [send logs to Honeycomb](https://vector.dev/docs/reference/configuration/sinks/honeycomb/).

**Comment by robinbb** [comment]
I think that we simply want to log to stdout/stderr, and little else.

**Comment by robinbb** [comment]
Done. Or, dup of #217
