### ISSUE TITLE
Calculate the total Mina supply for ledgers

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#494]
Add a `total_currency` function for aggregating the total supply of mina tokens at a given height.

Note: the calculation will be off by `0.000001000` until we incorporate the genesis block winner into the ledger.

**Comment by trevorbernard** [comment]
Proposal: we just ingest the 2 known bad genesis accounts and assign `0.000001000` to the genesis block winner after parsing the genesis mainnet ledger.

Alternatively, we might want to ingest the epoch 0 staking ledger. Not sure if that's a good idea or not -- but it will include the magic mina.

**Comment by trevorbernard** [comment]
An update: I've allowed the 2 known bad public keys into the genesis ledger and I've accounted for the genesis block winner in the genesis ledger.

**Comment by trevorbernard** [comment]
The total supply is simply the foldl sum account.balance. A good test would be to compare the calculated total supply at a given height and compare the total supply value in the block at that height. This test will fail until we resolve the following issue: https://github.com/Granola-Team/mina-indexer/issues/541

**Comment by robinbb** [comment]
@trevorbernard Is this required for equivalence with minaexplorer.com?

**Comment by jhult** [comment]
https://github.com/Granola-Team/mina-indexer/commit/edbd01b8802351188a38a2e70b12dfc7d4723941 may have resolved. I will compare and check.

**Comment by trevorbernard** [comment]
https://github.com/Granola-Team/mina-indexer/blob/3d41a221a95bd46ca6f8812afc7a2dd2ae824580/rust/src/ledger/mod.rs#L36

This is resolved
