### ISSUE TITLE
Calculate total circulating supply and expose via HTTP endpoint

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#496]
Use time-locked / vesting schedule info (from #876) and then subtract the aggregated [current_minimum_balances](https://github.com/MinaProtocol/mina/blob/master/rfcs/0025-time-locked-accounts.md#detailed-design) (for timed accounts) from Total (theoretical maximum) Currency.

Expose this total circulating supply via either REST or GraphQL.

**Comment by robinbb** [comment]
Needed for circulating supply calculation, I think.

**Comment by jhult** [comment]
Docs:
- https://docs.minaprotocol.com/mina-protocol/time-locked-accounts
- https://docs.minaprotocol.com/zkapps/o1js/time-locked-accounts
