### ISSUE TITLE
Consolidate functions that parse state hash from file names

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#503]
Consolidate and pick one

**Comment by n1tranquilla** [comment]
I can't assign this ticket to myself, but i'll take it

**Comment by robinbb** [comment]
@n1tranquilla Any progress on this issue?

**Comment by trevorbernard** [comment]
This is no longer being worked on. We're missing the requirements for when we need to validate vs. Parse really fast.

**Comment by jhult** [comment]
Fixed by https://github.com/Granola-Team/mina-indexer/pull/1512
