### ISSUE TITLE
Track `receipt_chain_hash` and `voting_for` for accounts

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#505]
Block explorers display this information with the account. Add `receipt_chain_hash` and `voting_for` to the Account Ledger.

**Comment by Isaac-DeFrain** [comment]
![image](https://github.com/Granola-Team/mina-indexer/assets/42081488/104f74fc-80d2-4b3b-ad1c-6f80162b11a4)
![image](https://github.com/Granola-Team/mina-indexer/assets/42081488/ec150878-4b1b-4e6c-8056-4af2733b9eda)

**Comment by jhult** [comment]
Possibly related to #748

**Comment by jhult** [comment]
First, we should log these two values (`receipt_chain_hash` and `voting_for`) in our modified Mina node.

**Comment by trevorbernard** [comment]
We decided that we won't do this a while back but this issue remains. Closing.
