### ISSUE TITLE
Enhancement: Merge Rust imports using rustfmt

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#509]
Use `imports_granularity = "Crate"` [in rustfmt](https://rust-lang.github.io/rustfmt/?search=&version=v1.6.0#imports_granularity) to merge Rust imports (for cleaner imports).

### What this does?

<img width="919" alt="image" src="https://github.com/Granola-Team/mina-indexer/assets/9849069/e9217da0-dc25-4460-ad3d-45574858cce5">

### Example
<img width="673" alt="image" src="https://github.com/Granola-Team/mina-indexer/assets/9849069/083e50dc-d5a9-4aa4-9807-a9d8e7a3d781">

**Comment by trevorbernard** [comment]
We should create a `rustfmt.toml` file for this. I would like to see comments wrapped to 80 chars
