### ISSUE TITLE
Problem: 'watchexec' version bump by dependabot results in build failure

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#536]
Probably, the problem is that the version bounds incorrectly permit a major version increase. Aside: do we really need 'watchexec'?

**Comment by robinbb** [comment]
@jhult Help wanted.

**Comment by jhult** [comment]
PR: https://github.com/Granola-Team/mina-indexer/pull/532

Related to #537. See [comment there](https://github.com/Granola-Team/mina-indexer/issues/537#issuecomment-1981222163) about version conflicts.

**Comment by trevorbernard** [comment]
Watch exec is the underlying library we use to watch file system events. We plan to replace this eventually with the much simpler notify-rs library (cargo uses this).
