### ISSUE TITLE
Problem: dependency 'async-priority-channel' next minor version not compatible with mina-indexer

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#537]
Perform code changes required to update to newer version of 'async-priority-channel'.

**Comment by jhult** [comment]
I'm looking into this.

**Comment by jhult** [comment]
[watchexec](https://crates.io/crates/watchexec) has a [dependency](https://crates.io/crates/watchexec/3.0.1/dependencies) on [async-priority-channel](https://crates.io/crates/async-priority-channel).

Unfortunately, the latest published version of `watchexec`, 3.0.1, still depends on `async-priority-channel` 0.1.0. This has been [updated on GitHub](https://github.com/watchexec/watchexec/blame/main/crates/lib/Cargo.toml#L19) but a new crate version has not yet been published.

So, I think we have to hold off on this until a new version of `watchexec` is published.

**Comment by robinbb** [comment]
> So, I think we have to hold off on this until a new version of `watchexec` is published.

The right thing to do is actually #548 .
