### ISSUE TITLE
Problem: fees are not correctly calculated and applied to the ledger

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#541]
Due to our misunderstanding about how Mina snark work fees work on `mainnet`, we incorrectly calculate and apply the fees to accounts on the ledger. As a result, we figured out the correct way to apply fees: https://gist.github.com/trevorbernard/78b8c43d111f6e4a45eaea582f033e7e

Fee transfers are computed from the `completed_works` of a staged ledger diff. Each fee transfer is a block producer paying out the requested fee for some newly included work from the snark pool. Fee transfers are computed from the list of work that was purchased.

**Comment by robinbb** [comment]
@trevorbernard The PR that claims to fix this is merged, but you may want to take a close look, to see if things are the way that you expect.
