### ISSUE TITLE
Problem: the `--ledger-cadence` command line switch has unclear semantics

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#544]

**Comment by Isaac-DeFrain** [comment]
It's used in `src/state/mod.rs` to batch apply ledger diffs and store a copy in the ledger store.

```
--ledger-cadence <LEDGER_CADENCE>
    Cadence for computing and storing ledgers [default: 100]
```

**Comment by trevorbernard** [comment]
@Isaac-DeFrain @robinbb What is unclear about this flag? The description is clear to me. With that being said, how are we going to resolve this? With documentation? Code comments?

**Comment by robinbb** [comment]
Better language for the switch and its help text. I'll take care of it.
