### ISSUE TITLE
Consolidate logic for precomputed block filenames with format `<network_name>-<state_hash>.json`

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#588]

**Comment by robinbb** [comment]
I went to a special effort to ensure that all log files (back to the one after genesis) have the correct name, in our Granola-local dev env, FYI.

**Comment by Isaac-DeFrain** [comment]
I think this issue pertains to the various helper functions originally written to support the now unsupported filename format `<network_name>-<state_hash>.json`

**Comment by n1tranquilla** [comment]
I think this is done now.

**Comment by jhult** [comment]
Closed by #1513
