### ISSUE TITLE
Log when doing re-orgs in database

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#608]
I recommend logging start and end time. We probably also want to periodically output a log statement about the progress.

**Comment by trevorbernard** [comment]
Compactions are already logged in the RocksDB LOG file. We may want to log to a custom file?

**Comment by jhult** [comment]
Related to #485

**Comment by jhult** [comment]
For more info on this, see #380.

**Comment by n1tranquilla** [comment]
During ingestion, there were minimal compactions, from what I could see, and they were quite efficient. I also tried manually compacting every 50k blocks, and logged out the interval, which revealed it was trivial ("0s").
