### ISSUE TITLE
Provide functionality to restore from a "snapshot"

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#613]

**Comment by Isaac-DeFrain** [comment]
What would the be the intended semantics for "restore from checkpoint"? `sync`/`replay` may already do what you want.

**Comment by robinbb** [comment]
"Restore from checkpoint" would take as input a tarball instead of a database directory.

**Comment by jhult** [comment]
The [`flate2` crate](https://lib.rs/crates/flate2) looks like it might be a good candidate for (de)compressing.
