### ISSUE TITLE
Problem: The indexer doesn't have a concept of a `production` release

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#619]
Follow the [Filesystem Heirachy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/index.html) for production releases.

- locked.cvs, genesis block and ledger should be read from `/usr/share/mina-indexer/data` 
- Indexer database stored in `/var/lib/mina-indexer/database`
- mina-indexer binary in `/usr/bin`

**Comment by trevorbernard** [comment]
Maybe we should use something along the lines of https://docs.rs/clap_conf/latest/clap_conf/ to unify the CLI args, env variables and config files?

**Comment by trevorbernard** [comment]
I think we need to set default values conditionally in `clap`. Production values point to the standard FHS otherwise maintain status quo.

**Comment by robinbb** [comment]
@trevorbernard I think that the 'nix build' generates a package that does indeed follow the FHS, and is usable as a production release. Are there any remaining directories or files to add? Here is what I have:

**Comment by robinbb** [comment]
```
|-- bin
|   `-- mina-indexer
|-- usr
|   `-- share
|       `-- mina-indexer
|           `-- data
|               |-- locked.csv
|               |-- mainnet-1-3NKeMoncuHab5ScarV5ViyF16cJPT4taWNSaTLS64Dp67wuXigPZ.json
|               `-- mainnet.json
`-- var
    |-- lib
    |   `-- mina-indexer
    `-- log
        `-- mina-indexer
```
