### ISSUE TITLE
Problem: the regression test suite answers are suspicious/wrong

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#628]

**Comment by trevorbernard** [comment]
<img width="931" alt="Screenshot 2024-03-19 at 1 53 47 PM" src="https://github.com/Granola-Team/mina-indexer/assets/8825/a53a5a03-a90e-49e4-96c9-173568f3a144">
<img width="1007" alt="Screenshot 2024-03-19 at 1 53 55 PM" src="https://github.com/Granola-Team/mina-indexer/assets/8825/677a7af7-3fc5-4555-beac-e873412dffb3">
<img width="980" alt="Screenshot 2024-03-19 at 1 54 04 PM" src="https://github.com/Granola-Team/mina-indexer/assets/8825/e7b43296-44b9-4d3e-b333-b684a76ce82c">
<img width="1066" alt="Screenshot 2024-03-19 at 1 54 11 PM" src="https://github.com/Granola-Team/mina-indexer/assets/8825/b61ee6e5-0dc4-4ba9-a8fb-5f31216b60c5">
<img width="1078" alt="Screenshot 2024-03-19 at 1 54 20 PM" src="https://github.com/Granola-Team/mina-indexer/assets/8825/6a69902c-8001-446e-8b9c-40c1ee42c011">
<img width="1019" alt="Screenshot 2024-03-19 at 1 54 26 PM" src="https://github.com/Granola-Team/mina-indexer/assets/8825/e93794a7-7700-4850-8127-6bcf70d665ff">
