### ISSUE TITLE
Problem: the indexer build times are very slow

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#637]
Incorporate some of these tips for faster compile times: https://corrode.dev/blog/tips-for-faster-rust-compile-times/

**Comment by Isaac-DeFrain** [comment]
I'm on `cargo features prune`

**Comment by trevorbernard** [comment]
> I'm on `cargo features prune`

I tried that a few weeks ago. You'll have to enable some features it thinks are unnecessary. I didn't invest much time trying to fix it.. I put it in a branch and moved on. YMMV

**Comment by robinbb** [comment]
Build times are pretty good, given that it's a "release" build. I have adjusted the caching on the main build machine so that build times are improved when possible. This is "done enough" for now, IMHO.
