### ISSUE TITLE
Problem: 'blocks_dir' nonexistence not handled (panics)

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#646]
No need for a 'blocks_dir' to exist at all, especially when a database is present.

**Comment by robinbb** [comment]
@Isaac-DeFrain I want to up-prioritize this, as it will help with the logic related to default directories. Is it possible for the indexer to treat the blocks_dir as optional?

**Comment by Isaac-DeFrain** [comment]
Yes, we can start a fresh indexer without ingesting blocks from a directory

**Comment by Isaac-DeFrain** [comment]
If we make the blocks dir optional, we will need a way to tell the indexer to start watching a directory for blocks while it's running

**Comment by Isaac-DeFrain** [comment]
Currently, even when you `sync` or `replay` from an existing db, we use the blocks watch dir to continue ingesting any new blocks

**Comment by robinbb** [comment]
Right, so the watch_dir now cannot have as its default the blocks_dir if the blocks_dir is unset. The watch dir can be whatever is the default directory for the logs of the Mina node, in that case, I propose.

**Comment by Isaac-DeFrain** [comment]
We have the ability to choose that default in the Mina node since we implemented it. Should it be `/usr/share/mina/blocks`?

**Comment by Isaac-DeFrain** [comment]
Does it make sense to have both directories as optional and when
- `blocks_dir` set   => `block_watch_dir` defaults to `blocks_dir`
- `blocks_dir` unset => `block_watch_dir` is the above default
