### ISSUE TITLE
Problem: we don't index internal commands

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#654]

**Comment by trevorbernard** [comment]
Store internal commands (fee transfer, coinbase, fee transfer via coinbase) making sure to include it's parent block's state_hash.

**Comment by Isaac-DeFrain** [comment]
User commands are indexed on:
- public keys
- state hash of block
- command/transaction hash

AFAIK internal commands do not have hashes associated with them. We'll index internal commands on:
- public keys
- state hash of block
