### ISSUE TITLE
Support querying multiple networks

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#655]
We should expand the cli query args to have an optional flag `--network` which defaults to `"mainnet"`

**Comment by jhult** [comment]
@Isaac-DeFrain, you mean a global option/flag for all commands?

**Comment by jhult** [comment]
Related to #650.

**Comment by robinbb** [comment]
Perhaps so, but this begs the question: will the indexer work with 2 different networks simultaneously? Or, maybe we need to work with *some* network, but only one network.

**Comment by Isaac-DeFrain** [comment]
My thinking is that we now index almost everything in the db by network so it is possible to make queries on multiple networks. The indexer will only ever be "running" on one network at a time but that network may change, e.g. with the hardfork. I'm envisioning the indexer running on current mainnet and having the ability to upgrade to the new network without downtime, after which we can query all old and new network data
