### ISSUE TITLE
The default config options are broken on macOS

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#662]
```
$ mina-indexer server start
Error: Permission denied (os error 13)
```

The problem is that on darwin system, it protects the `/usr` directory

**Comment by jhult** [comment]
Just bumped into the same. The `log` directory has issues too. I think the following may have worked around the log directory issue for me:
```
sudo mkdir -p /var/log/mina-indexer/
sudo chown -R jonathan:admin /var/log/mina-indexer/
```

**Comment by jhult** [comment]
Cause: https://github.com/Granola-Team/mina-indexer/commit/edc5a07f10b8c3928f545f3cea3733ccafee2487 via #648

**Comment by Isaac-DeFrain** [comment]
Is this issue resolved? @jhult solution worked for me

**Comment by jhult** [comment]
This makes running and testing on macOS tricky as you have to be sure to apply a [workaround](https://github.com/jhult/mina-indexer/commit/57bab1908fd7f5e333e6308a94aebecd1776c80b).

**Comment by trevorbernard** [comment]
This is my work around. This exists in the root of the rust directory:

```bash
#!/usr/bin/env bash

BLOCKS_DIR=~/.mina-indexer/blocks
STAKING_LEDGERS_DIR=~/.mina-indexer/staking-ledgers
GENESIS_LEDGERS_DIR=~/.mina-indexer/genesis-ledgers
DATABASE_DIR=~/.mina-indexer/database

IDXR="$(pwd)"/target/release/mina-indexer
DOMAIN_SOCKET_PATH="$(pwd)"/mina-indexer.sock

mina-indexer() {
    "$IDXR" "$@"
}

mina-indexer server start \
        --blocks-dir "$BLOCKS_DIR" \
        --staking-ledgers-dir "$STAKING_LEDGERS_DIR" \
        --database-dir "$DATABASE_DIR" \
        --log-level debug 2>&1
```

**Comment by robinbb** [comment]
Blocked on #920 and #921. After those are complete, then all that remains is to set good defaults for blocks directory and staking ledgers directory.

**Comment by robinbb** [comment]
Also blocked on #1082 .

**Comment by robinbb** [comment]
I no longer use Nix on my MacOS machine, so it is difficult for me to work on this issue.

Since the Indexer is a server, then by the Linux FHS, one would expect the logs in /var/log/mina-indexer despite the fact that this is a read-only directory for non-root users.

So, @jhult, what is the status of this issue, now that various blocking issues have changed? Do we expect to be able to start the server without arguments when we are not root?

**Comment by jhult** [comment]
As long as you set `VOLUMES_DIR` to a writable directory, this is no longer an issue.

Example: `export VOLUMES_DIR="~/.mina-indexer"`

**Comment by jhult** [comment]
Related: https://github.com/Granola-Team/mina-indexer/issues/1272

**Comment by robinbb** [comment]
> As long as you set `VOLUMES_DIR` to a writable directory, this is no longer an issue.

I'll close, since this is no longer an issue.
