### ISSUE TITLE
Problem: we cannot start the indexer from `config.json`

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#665]
The indexer previously had the ability to start from a config file. That feature was never tested, ultimately it broke and was removed. We should resurrect this feature

**Comment by jhult** [comment]
Related to #666 and #650.

**Comment by robinbb** [comment]
Not sure I agree that this is a problem. This is a feature request to add the ability to provide a JSON file instead of configs to a sever start command, perhaps?

**Comment by Isaac-DeFrain** [comment]
I added some more context above (sorry, I thought I did that before).

**Comment by robinbb** [comment]
I still do not agree that this feature is required. My view is that they existence of the config.json is the problem. See #675

**Comment by Isaac-DeFrain** [comment]
We can remove it
