### ISSUE TITLE
SNARK work IDs are not included in PCBs

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#693]
SNARK proofs contain a lot of info in the PCB, but not work id. To recreate this calculation, we would have to implement a toy version of the [SNARK pool](https://github.com/openmina/openmina/tree/main/node/src/snark_pool)

**Comment by robinbb** [comment]
... or instrument the Mina node to log it?

**Comment by Isaac-DeFrain** [comment]
Is that the preference? Either option is fine to me

**Comment by jhult** [comment]
Relates to https://github.com/Granola-Team/mina-block-explorer/pull/588
