### ISSUE TITLE
Investigate how to stream large JSON GQL responses

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#695]
Stakes API returns large amounts of data. See if it's possible to stream JSON early

**Comment by jhult** [comment]
Would WebSockets be helpful here?

**Comment by trevorbernard** [comment]
> Would WebSockets be helpful here?

No, the problem is that it builds the payload first before sending it to the client.

**Comment by trevorbernard** [comment]
There is no easy way to to stream lists of things that would benefit us. Closing
