### ISSUE TITLE
Problem: need Mina PCB logging PR in our repo

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#696]

**Comment by jhult** [comment]
Related:
- https://github.com/MinaProtocol/mina/pull/13236
- https://github.com/Granola-Team/mina-indexer/issues/211

**Comment by Isaac-DeFrain** [comment]
This task was for the pre-berkeley network

**Comment by Isaac-DeFrain** [comment]
Adding another for post-berkeley network
