### ISSUE TITLE
Problem: GQL stakes and block endpoint are missing tests

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#698]

**Comment by jhult** [comment]
Implementations:

- https://github.com/Granola-Team/mina-indexer/issues/553
- https://github.com/Granola-Team/mina-indexer/issues/557

**Comment by jhult** [comment]
A few possible tools:
- [hurl](https://hurl.dev/)
- [graphql-to-karate](https://github.com/wbaldoumas/graphql-to-karate)
- [k6](https://github.com/grafana/k6)
- [Step CI](https://github.com/stepci/stepci)

**Comment by jhult** [comment]
Block(s) implemented via https://github.com/Granola-Team/mina-indexer/pull/792 and https://github.com/Granola-Team/mina-indexer/pull/797

**Comment by jhult** [comment]
Stakes added in #800
