### ISSUE TITLE
Problem: supplying path argument to transactions state hash CLI does nothing

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#725]
It should write the transaction to the specified path.

https://github.com/Granola-Team/mina-indexer/blob/main/rust/src/unix_socket_server.rs#L1084

**Comment by jhult** [comment]
[It looks like](https://github.com/Granola-Team/mina-indexer/blob/a97a5ceaa4774043ae6e99264fba4364062b3b6d/rust/src/client.rs#L623) it was broken before [the refactor](#650) as well (just not as obvious).
