### ISSUE TITLE
Support the archive node API from O(1) Labs

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#735]
https://github.com/o1-labs/archive-node-api

**Comment by trevorbernard** [comment]
Note: https://github.com/Granola-Team/mina-indexer/issues/357

**Comment by jhult** [comment]
@robinbb, is this a dupe of #357?

**Comment by robinbb** [comment]
> @robinbb, is this a dupe of #357?

Unknown.

**Comment by Isaac-DeFrain** [comment]
Closing as it is a dupe of #357
