### ISSUE TITLE
Cannot retrieve a single next staking ledger via GraphQL

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#752]

**Comment by jhult** [comment]
#558 is for stakes (plural)

**Comment by Isaac-DeFrain** [comment]
Can we close this issue?

**Comment by robinbb** [comment]
@trevorbernard You opened this, so I propose that you decide.

**Comment by trevorbernard** [comment]
Let's close it. IMHO, that's a useless API since it doesn't fetch a single epoch but a single account.
