### ISSUE TITLE
Indexer does not always shutdown cleanly

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#767]
SIGTERM is not sufficient to kill Indexer.

**Comment by jhult** [comment]
https://github.com/Finomnis/tokio-graceful-shutdown seems like it would help.

**Comment by jhult** [comment]
Related to #1144

**Comment by robinbb** [comment]
The test is still commented out in 'regression.bash', and this is still not solved. Not sure why the issue was closed. When the Indexer is killed with SIGINT/SIGTERM, it fails to handle the socket.
