### ISSUE TITLE
Add pagination to all GraphQL endpoints to support frontend 

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#783]

**Comment by trevorbernard** [comment]
This is a substantial amount of work and needs more information. For example, do we want pagination to be cursor based or offset based?

**Comment by jhult** [comment]
[Here](https://docs.blockberry.one/reference/pagination) is some info on how others achieve pagination.

**Comment by jhult** [comment]
Some reading: https://graphql.org/learn/pagination/

**Comment by robinbb** [comment]
Not strictly required. Closing. (Use limits or filters to reduce result set size.)
