### ISSUE TITLE
Learn and document how Berkeley ledgers should be maintained with zkApps

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#840]
- [x] learn
- [ ] document

**Comment by trevorbernard** [comment]
@Isaac-DeFrain In `mainnet`, implicitly all addresses (ledgers) are of type 1. We don't explicitly represent it that way but we will need to handle that in the post hard-fork chain. To uniquely identify an account, we will need to treat it as a tuple: `(public_key, token_id)`.
