### ISSUE TITLE
Merges are allowed before CI pipeline has completed successfully

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#854]
### Example:

<img width="924" alt="image" src="https://github.com/Granola-Team/mina-indexer/assets/9849069/11c143a1-7365-4a31-b92b-aadc96d90bbf">

**Comment by robinbb** [comment]
@jhult I think that this is corrected, now, via changes to settings in both Buildkite and GitHub (no code changes to reflect this, alas). Please verify.

**Comment by jhult** [comment]
This still seems to be a problem

![Screenshot_20240518-151528](https://github.com/Granola-Team/mina-indexer/assets/9849069/dfcef472-bc81-476d-81a4-73a6e6260e06)

**Comment by robinbb** [comment]
@jhult New status on this: I believe that it is possible to add the PR to a merge queue before the CI for the PR (by itself) completes. That makes sense, but also the user should be able to configure this on/off. Based on the GitHub settings for this repo, it *should* be that promoting the PR to the merge queue before it has passed CI is *disallowed*. However, it seems that some settings are simply disregarded if there is a merge queue. Worse, the PR is marked "merged" before either CI run (the PR's run, or the merge queue's run) have succeeded. Yet worse still, GitHub closes/deletes the branch used to run the merge queue after it completes, leaving no evidence of what happened. Did it pass the merge queue? Or, did it fail, and the PR regardless closed?

**Comment by robinbb** [comment]
I have reverted the "merge queue" functionality. It still may be that  merges are allowed before the CI checks have passed. Let me know, @jhult .
