### ISSUE TITLE
Add `block production %age` to the (next)stakes GQL endpoints

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#855]
We need way to obtain the block production percentage per account per epoch.

**Comment by jhult** [comment]
Needed for https://github.com/Granola-Team/mina-block-explorer/issues/502

**Comment by trevorbernard** [comment]
In order for us to have an equivalent front-end (even though ME's API is private), we must provide the following the `block win %ge` calculation for every account per epoch. Augment the (next)stakes GQL API to include this calculation.

**Comment by Isaac-DeFrain** [comment]
The idea:

We will maintain two column families:
```
accountCF: {epoch BE}{pk} -> # of blocks produced by pk in epoch
epochCF:   epoch -> # of blocks produced in epoch
```

- `accountCF` maintains _per account_ totals
- `epochCF` maintains _per epoch_ totals

**Comment by Isaac-DeFrain** [comment]
After further thought, it doesn't make sense to report blocks produced in the _next_ epoch. It's always 0.
