### ISSUE TITLE
Regression suite failing locally due to `pwait` in nix shell

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#887]
```shell
nix develop
./tests/regression test_server_startup
```

Notice error: `timeout: failed to run command ‘pwait’: No such file or directory`

**Comment by trevorbernard** [comment]
I'm wondering if this is strictly a mac only issue? The CI server uses nix and doesn't fail

**Comment by trevorbernard** [comment]
It's is an `aarch64-darwin` specific issue. https://hydra.nixos.org/job/nixos/release-23.11/nixpkgs.extrace.i686-linux#tabs-links The procps says it includes an `aarch64-darwin` build but it doesn't.

**Comment by robinbb** [comment]
I think this is "won't do". Prior, I have discussed limiting the "supported" platform to Linux. Others opposed, and desired to have macOS be supported. With Mac, there is M1/M2/M3/M4 chips to support, and Intel. This means that there are really 2 Mac environments and 1 Linux environment, for a total desired of 3. I think that we cannot afford to alot effort to supporting 3 dev environments when we only support 1 runtime environment (Linux).

**Comment by trevorbernard** [comment]
@robinbb Unfortunately, I disagree with not supporting running our tests on aarch64-darwin. Relying on CI/CD to see if our tests pass is too slow.
