### ISSUE TITLE
Problem: (next)stakes GQL endpoint returns accounts in an indeterministic manner

### ISSUE THREAD

**Issue by trevorbernard** [Granola-Team/mina-indexer#890]
The MinaExplorer stakes API doesn't support sorting by stake so we will be default return in stake sorted order.

**Comment by Isaac-DeFrain** [comment]
By "stake sorted order" do you (also) mean "total delegations sorted order"?

**Comment by Isaac-DeFrain** [comment]
Is this a non-issue since `nextStakes` was removed?

**Comment by trevorbernard** [comment]
@Isaac-DeFrain Good point. #yeet
