### ISSUE TITLE
Set/Store account usernames in db

### ISSUE THREAD

**Issue by Isaac-DeFrain** [Granola-Team/mina-indexer#896]
Payment to the Mina Explorer Name Service address of 0 MINA and memo prefixed with `Name: `

**Comment by Isaac-DeFrain** [comment]
https://docs.minaexplorer.com/minaexplorer/explorer-name-service

**Comment by robinbb** [comment]
It appears that, in addition to the "Name:" protocol described, there was an initial set of names collected on a staketab.com webpage. The latter is now defunct. See https://web.archive.org/web/20210209230353/https://mina.staketab.com/ for the list of 184 names.

I propose that you try to discover those same names via the protocol. Then, assign to me and I will produce a CSV (by manually typing in the names) that you can incorporate into the indexer.

**Comment by Isaac-DeFrain** [comment]
Will we allow multiple accounts to have the same username?

**Comment by Isaac-DeFrain** [comment]
It's interesting that anyone can name themself `MinaExplorer Name Service` for example

**Comment by Isaac-DeFrain** [comment]
For the time being, I'll just look at txns to the ME name service address
