### ISSUE TITLE
Missing GraphQL endpoints for Berkeley for frontend

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#902]
As we find missing endpoints, create issues for those.

Ideally `hurl` test(s) will be setup (they can't run because they won't pass without implementation) for each endpoint.

**Comment by jhult** [comment]
Relates to #357

**Comment by jhult** [comment]
@Isaac-DeFrain offered to assist.

**Comment by robinbb** [comment]
Related to Granola-Team/mina-block-explorer#645

**Comment by trevorbernard** [comment]
I added issues for creating the various GQL endpdoints for the project
