### ISSUE TITLE
Problem: the locked.csv is awkward to deploy and should be part of the binary

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#920]
The idea is to render unnecessary the "--locked-supply-csv <path-to-locked-supply-csv-file>" command line switch by including the file verbatim in the mina-indexer binary. This means that we won't need to parse a file, but a static string.

This is important because it is very error-prone to ensure that the file is installed into the right place on the user's machine.

This makes the Nix-built image more difficult to get right.

Old requirement:

... results in awkward unnecessary addition of things like:
```
--locked-supply-csv "$SRC"/data/locked.csv \
```
lines on invocations, plus the need to deploy that to some known location somewhere on the target machine.

**Comment by robinbb** [comment]
Use https://doc.rust-lang.org/std/macro.include_str.html to just pull the contents of the file into the binary at compile time, I suggest.

**Comment by jhult** [comment]
Related to #921
