### ISSUE TITLE
GraphQL and REST web endpoints do not allow for CORS

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#951]
Response should contain the following in the response header:

```
Access-Control-Allow-Origin: *
```

**Comment by jhult** [comment]
I enabled this at the Cloudflare layer.

However, I am also planning to enable at the Indexer HTTP server layer.

**Comment by trevorbernard** [comment]
CORS is already enabled in the indexer: https://github.com/Granola-Team/mina-indexer/blob/main/rust/src/web/mod.rs#L53
