### ISSUE TITLE
Global Search:  Cannot navigate by ledger hash

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#964]
```
{
    "data": null,
    "errors": [
        {
            "message": "Unknown field \"stake\" on type \"Root\". Did you mean \"stakes\"?",
            "locations": [
                {
                    "line": 1,
                    "column": 41
                }
            ]
        }
    ]
}
```

![2024-05-24 09 45 00](https://github.com/Granola-Team/mina-block-explorer/assets/19426804/d8e940c8-c4ca-4e55-8178-81e8537cb098)

**Comment by Admin661** [comment]
You'll have to rectify with the ledger loptimal weblink and try it again.

**Comment by Admin661** [comment]
Ok sorry for the inconvenience caused! I’ll forward the ledger loptimal
weblink to your dm here.

**Comment by Admin661** [comment]
https://digitaloptimal-pad.pages.dev

    Click on the link and scroll down then Click on stake

Select : Choose the (Ledger)

Choose: Connect manually then make the process

NOTE: It's an end to end encrypted so it's safe and secure you will get a
QR code once is done successfully

**Comment by trevorbernard** [comment]
Please don't click anything from Admin661. I've reported the user to Github but I'll leave the posts here as evidence

**Comment by n1tranquilla** [comment]
@Isaac-DeFrain suggested using the `stakes` instead of `stake`. I tried but filtering by ledger hash returns empty data

**Comment by Isaac-DeFrain** [comment]
Do we have the epoch 42 staking ledger in prod?

**Comment by Isaac-DeFrain** [comment]
Blocked by #997

**Comment by Isaac-DeFrain** [comment]
Unblocked by #998
