### ISSUE TITLE
Unsure what git commit an Indexer is running

### ISSUE THREAD

**Issue by jhult** [Granola-Team/mina-indexer#971]
Add a REST endpoint (e.g. `/version` or `/about`) that provides the git commit (`'git rev-parse --short=8 HEAD`) this Indexer instance was built against.

Note that the `--version` for the CLI returns `mina-indexer 0.1.1` (due to [this](https://github.com/Granola-Team/mina-indexer/blob/968e2558e712ea8eea6ab81b702d2fca8e0f0c0c/rust/Cargo.toml#L3) in `Cargo.toml`). We want the version (CLI command) to be the git commit (or perhaps something like [Calendar Versioning](https://calver.org/)).

**Comment by jhult** [comment]
This relates to https://github.com/Granola-Team/mina-block-explorer/issues/698 and the implementation [PR #702](https://github.com/Granola-Team/mina-block-explorer/pull/702/files#diff-2f90408c2b0302b1cdb7f5d634114750837f940fa82d13057d9c18d0170a7e5cR12):

<img width="808" alt="image" src="https://github.com/Granola-Team/mina-indexer/assets/9849069/ec0faa0e-9f9e-42a3-b02f-0ba418463b35">

**Comment by trevorbernard** [comment]
I was going to suggest adding a `build.rs` but you beat me to it. You could use something like the `BUILDKITE_COMMIT` env variable to set this value in CI/CD

**Comment by robinbb** [comment]
For consistency, please use the output of 'git rev-parse --short=8 HEAD', run at build time.

**Comment by trevorbernard** [comment]
For simplicity sake, I fixed the CLI version command to include the git commit hash. If we really want to add an API, it should be another issue.
