### ISSUE TITLE
Make CI secure against foreign repos

### ISSUE THREAD

**Issue by robinbb** [Granola-Team/mina-indexer#977]

**Comment by jhult** [comment]
[Cross-linking](https://github.com/Granola-Team/mina-block-explorer/issues/44#issuecomment-1932579518) to some helpful info from the `mina-block-explorer` repo.

**Comment by robinbb** [comment]
Solution:

1. Use Buildkite permissions to split CI into multiple tiers (tier-1, tier-2, etc.) for which only select individuals have access to tiers 2 and above.
2. Only tier-1 is required to successfully merge a PR.
3. In tier-1 CI machines, there are no credentials required to deploy, etc. So, in case a tier-1 CI machine is abused, only compute resources are lost. (Same as with GitHub Actions, for example.)
4. Production deployments do not come same machine(s) as tier-1 CI.
5. Distributed binaries are not built on tier-1 CI.
