### ISSUE TITLE
Staking ledger: Epoch 42 is not performant and sometimes crashes

### ISSUE THREAD

**Issue by n1tranquilla** [Granola-Team/mina-indexer#979]

**Comment by robinbb** [comment]
At present, there are only 2 staking ledgers in the staking ledgers directory. One of them is for epoch 42. Maybe our logic assumes that we have all ledgers *up to* the ledger that we're querying? (Just an idea about what to look for.)

**Comment by trevorbernard** [comment]
This is no longer an issue
